### ISSUE TITLE
Always set original location to null when authkey is not empty

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#118]
https://github.com/SUPLA/supla-cloud/blob/591646defdc049438f57289f246360379daeeb33/src/SuplaBundle/Entity/IODevice.php#L156

**Comment by fracz** [comment]
Why supla server does not set the originalLocationId when registering with access id? If it would, we won't have to remember it in cloud.

**Comment by przemyslawzygmunt** [comment]
Canceled.
