### ISSUE TITLE
The "start" page does not display properly on smartphone screens

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#125]
![img_1092](https://user-images.githubusercontent.com/6603397/30002570-bcc58824-90ac-11e7-9673-86e5b16cefd8.PNG)

**Comment by fracz** [comment]
![animation 0](https://user-images.githubusercontent.com/3918865/30374054-d38f9bec-9883-11e7-9dcf-43693f776f03.gif)
