### ISSUE TITLE
Delete dialog box does not display properly on smartphone screens

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#126]
![img_1093](https://user-images.githubusercontent.com/6603397/30002578-f854dc46-90ac-11e7-8582-2eec9390eaa7.PNG)

**Comment by fracz** [comment]
![supla dev-client-apps iphone 5](https://user-images.githubusercontent.com/3918865/30003921-f28ad518-90c5-11e7-916f-c3df03b86bf1.png)
