### ISSUE TITLE
Gate channel properties -  add option "Automatic close when open longer than x minutes."

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#128]
https://github.com/SUPLA/supla-core/issues/37

**Comment by przemyslawzygmunt** [comment]
https://forum.supla.org/viewtopic.php?f=23&t=2008&p=11705#p11705

**Comment by fracz** [comment]
“Zamknij jeśli otwarta dłużej niż…. w godzinach od do”

**Comment by przemyslawzygmunt** [comment]
"Zamknij po" tam może być poślizg 1 min z uwagi na to, że zadanie sprawdzania odpalane jest co min. Warto tam gdzieś wcisnąć taką informację. Może dodać tam (i) z informacją "Agent uruchamiający procedurę zamykania może mieć maksymalnie jednominutowe opóźnienie w stosunku do zadanego czasu"

**Comment by fracz** [comment]
![image](https://user-images.githubusercontent.com/3918865/198303237-6f19af55-b799-4f12-baf3-b2108cdb922e.png)
