### ISSUE TITLE
Set theme color for mobile device browsers

### ISSUE THREAD

**Issue by fracz** [SUPLA/supla-cloud#155]
https://developers.google.com/web/updates/2014/11/Support-for-theme-color-in-Chrome-39-for-Android

<meta name="theme-color" content="#SUPLA_GREEN">

**Comment by fracz** [comment]
Before: 
![image](https://user-images.githubusercontent.com/3918865/32808336-fc850236-c992-11e7-8350-4f63b1ea130a.png)

After:
![image](https://user-images.githubusercontent.com/3918865/32808351-095ee13e-c993-11e7-8154-4c23b2840aee.png)

@przemyslawzygmunt chcemy tak?

**Comment by przemyslawzygmunt** [comment]
Go for it
