### ISSUE TITLE
Database Error 

### ISSUE THREAD

**Issue by sanyaade-iot** [SUPLA/supla-cloud#156]
Hello Everybody,

follow the steps to set-up the server locally but ran into issues with the database drop and populate for the supla_client table as shown below:

`ipv4' at row 1  """] []
14:35:16 ERROR     [console] Command "supla:dev:dropAndLoadFixtures -e dev" exited with code "1" ["command" => "supla:dev:dropAndLoadFixtures -e dev","code" => 1] []
                                                                     
  [Doctrine\DBAL\Exception\DriverException]                                                                                                                                          
  An exception occurred while executing 'INSERT INTO supla_client (guid, name, enabled, reg_ipv4, reg_date, last_access_ipv4, last_access_date, software_version, protocol_version,  
   auth_key, access_id, user_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [7150452, "HTC One M8", 0, 6108856887044734977, "2017-09-03 07:14:58", 381744354201645875  
  3, "2017-10-11 10:29:18", "1.43", 27, null, null, 1]:                                                                                                                              
  SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'reg_ipv4' at row 1                                                                                
                                                                                              
  [Doctrine\DBAL\Driver\PDOException]                                                                  
  SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'reg_ipv4' at row 1  
                                                                                                
  [PDOException]                                                                                       
  SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'reg_ipv4' at row 1  
                                                                                                    
supla:dev:dropAndLoadFixtures [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

sanyaade@ns1:/var/www/html/site21/supla-cloud-2.1.1$ 
`
I am very new with Supla-Cloud. Please help!

God blesses!!!

Best regards,
Sanyaade

**Comment by fracz** [comment]
Are you trying to run the SUPLA-Cloud in order to develop or use it? Because the command you have mentioned is for development only.

**Comment by sanyaade-iot** [comment]
@fracz : 

Many thanks for your quick reply. Much appreciated!

I will be developping and also to use it. I will like to develop with it first.
How can I sort out the database issue? Please help!
Where can I learn more about Supla-Cloud

Hear from you soon!

God blesses!!!

Best regards,
Sanyaade

**Comment by fracz** [comment]
There was a bug in the Client's fixture. Can you please verify if you can load sample data on the newest `master`?

**Comment by sanyaade-iot** [comment]
Got another errors shown below:

>     
                                                                                                                              
  [Doctrine\DBAL\Exception\DriverException]                                                                                         
  An exception occurred while executing 'INSERT INTO supla_dev_channel (channel_number, caption, type, func, flist, param1, param2  
  , param3, alt_icon, hidden, iodevice_id, user_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [0, null, 2900, 140,   
  null, "", "", "", "", 0, 1, 1]:                                                                                                   
  SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'param1' at row 1                                     
                                                                                   
  [Doctrine\DBAL\Driver\PDOException]                                                            
  SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'param1' at row 1  
                                                                                 
  [PDOException]                                                                                 
  SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'param1' at row 1  

            
God blesses!!!

Best regards,
Sanyaade

**Comment by sanyaade-iot** [comment]
Hi @fracz 

How do I install samples into Supla-Cloud. Got Supla-Cloud running but only presented with an empty Vue webpage. I have tried installing the samples as specified on the github page but no success. Many thanks!
Supla-Cloud runs but showing empty webpage.

God blesses!!!

Best regards,
Sanyaade

**Comment by fracz** [comment]
What version of PHP and MySQL are you running?

**Comment by sanyaade-iot** [comment]
@fracz 
Hello fracz,

My PHP is 7.0.22 while MySQL is: mysql  Ver 14.14 Distrib 5.7.20

Hear from you soon!

God blesses!!!

Best regards,
Sanyade

**Comment by fracz** [comment]
The empty webpage problem is definitely not a result of lack of samples. Have you built the sources with `composer run-script webpack`?

**Comment by sanyaade-iot** [comment]
@fracz 

Yes! I went through all the steps as outline in Readme.md on this repository

I will give it a go on my Centos 7.0 to see if the problems are related to Ubuntu 16.04.
Also I will be learning Symfony to horn my skills since supla-cloud is a symfony package.
I will get back to you on my Centos trial today.

God blesses!!!

Best regards,
Sanyaade

**Comment by fracz** [comment]
The README is vague and we know this. It definitely should not be considered as a step-by-step tutorial, unfortunately.

Nevertheless, even if you was not able to load fixtures (sample data), you should be able to create an account and log in.

**Comment by sanyaade-iot** [comment]
@fracz 

Haah! So the README install steps should not be adhere to. 

Is a there any/another install direction that I could use?

I will appreciate your pointer and directions. Many thanks!

I have the same result on Centos 7 with blank page, no login page. I am still working and try many other options.

Hear from you soon!

God blesses!!!

Best regards,
Sanyaade

**Comment by fracz** [comment]
You should not open the https://localhost:25787/ in browser page as it is webpack dev server and it serves the frontend sources only (JS & CSS). You should go to the address that is mapped to the `web` directory. For example, it could be `https://localhost/supla/web`. You can also create a [Virtual host](https://httpd.apache.org/docs/2.4/vhosts/examples.html) that will map to `/var/www/supla/web` (or wherever you have installed it) and access cloud via nice fake local domain.

**Comment by fracz** [comment]
Check if that helps somehow: https://github.com/SUPLA/supla-cloud/blob/master/Development.md

**Comment by sanyaade-iot** [comment]
@fracz 
Okay, many thanks for your reply. I will give a try tonight when I get home from work. Also I may be having an application already using port 443. Is possible to change Supla-Cloud ssl port? Where in Supla-Cloud can I change ports or recongfigure Supla-Cloud ports.

Once again, many thanks! Really appreciated
Hear from you soon!

God blesses!!!

Best regards,
Sanyaade

**Comment by fracz** [comment]
This is because until today, SUPLA Cloud required you to work in SSL mode even in development mode. I have closed the #47 today so you won't bother about SSL certs for dev environment. I suggest you to try from scratch with the newest `master` branch and the docs I have provided.

**Comment by sanyaade-iot** [comment]
@fracz 

Gave supla-cloud a go again on Windows 7 64Bit just now but got uncaught symfony error message as shown below:

![image](https://user-images.githubusercontent.com/7230207/32682676-2639cd8c-c66e-11e7-9f15-ed5a36f95a90.png)

Still working with it for possible solution
Hear from you soon!

God blesses!!!

Best regards,
Sanyaade

**Comment by sanyaade-iot** [comment]
@fracz 
Update: I went round examining some of supla-cloud forks and gave the one at github.com/IOTAqua/supla-cloud a try.

I was able to setup supla-cloud as shown in the screenshot below:
![image](https://user-images.githubusercontent.com/7230207/32685145-7b494e1e-c683-11e7-9e33-0156361b220d.png)

My only problem now is the login page does not accept: user@supla.org and pass for login.
Creating a new account does not help either, even using a user name with gmail account and password does not work. 
I am now poking around the code to see user account could pre-configured for accessing the login-page.

I am still playing around with the newest master from Supla github

Hear from you soon!

God blesses!!!

Best regards,
Sanyaade

**Comment by fracz** [comment]
My bad. There was an error in setting the env variable. Have a look at the fix: https://github.com/SUPLA/supla-cloud/commit/bb8fcf1a465ad919f72a5d274c4e95200dfb9d3a

It should be `SetEnv APPLICATION_ENV dev`. After this change and restart of the XAMPP, the `http://supla.dev` should be working on our main repo.

Sorry for the mistake.

**Comment by sanyaade-iot** [comment]
@fracz 

Yes! I was now able to login into Supla-Cloud changing the setting you mentioned above. See the screenshot below:
![image](https://user-images.githubusercontent.com/7230207/32691060-297e1746-c6fa-11e7-9ea4-64e32b71a9cd.png)

1. I am also looking at generating user account locally on command line or whatever. (user details in the database e.g. SQLite or MySQL or other databases will a good features)
2. Get the other method running --> github.com/IOTAqua since this does not require nodejs running.
3. Study Symfony on how to extend supla-cloud
4. Write some articles on using supla-cloud, supla API and other modules, clients, etc....
5. I will now try this out on Ubuntu and Centos server and feedback to you. Many thanks!

@fracz:  Many, many thanks for your support and encouragement. really appreciated everything you have done for me so far.

Hear from you soon!

God blesses!!!

Best regards,
Sanyaade

**Comment by fracz** [comment]
1. There is no such option currently but feel free to add such command. There are [two sample commands so far](https://github.com/SUPLA/supla-cloud/tree/master/src/SuplaBundle/Command) you can use as an example. Also, to clarify, SUPLA CLoud is tested and officially supported on MySQL only. While it should work on other "real" RDMSs like PostgreSQL, I really doubt you will manage to launch it on SQLite.
2. As far I can see, the fork you have mentioned does not add anything in the SUPLA Cloud sources but the Readme with some instructions. Moreover, it does run `composer run webpack` so it needs NodeJS, too. You have to distinguish between development instance built from sources (NodeJS required to build Vue.js components) and production instance installed from an archive published with each release (both backend and frontend sources are already built and optimized so no need for NodeJS here).
3. Good luck!
4. As for the API, we are currently working on automated API docs generation, it should be live in v2.2.
5. Good luck!

Have a look at our forum - more people are reading there so you will have a greater chance of faster response: https://forum.supla.org/

Closing this as the initial problem has been solved.

**Comment by sanyaade-iot** [comment]
@fracz 

I am already on the forum since last month following all trends and using Google translate when neccessary. Many thanks!

I will also examine the production release side of Supla-Cloud and other points you have raised above.
Many thanks! 

See you at the forum.

God blesses!!!

Best regards,
Sanyaade
