### ISSUE TITLE
PHP7.x compatibility

### ISSUE THREAD

**Issue by iro88** [SUPLA/supla-cloud#157]
https://secure.php.net/supported-versions.php

**Comment by przemyslawzygmunt** [comment]
SUPLA-CLOUD is already compatible with PHP 7.x

**Comment by iro88** [comment]
Oh, sorry, I miss that. Why you don't use language features like strict type?

**Comment by fracz** [comment]
It was started for PHP 5.6. We have not reviewed the whole codebase just for sake of adding types there. The new code we are writing uses this feature, though.
