### ISSUE TITLE
Unable to generate a URL for the named route “_temp_unavailable” as such route does not exist.

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#158]
https://github.com/SUPLA/supla-cloud/blob/master/src/SuplaBundle/Supla/ServerList.php#L198

https://github.com/SUPLA/supla-cloud/blob/master/src/SuplaBundle/Controller/AccountController.php#L138

request.CRITICAL: Uncaught PHP Exception Symfony\Component\Routing\Exception\RouteNotFoundException: “Unable to generate a URL for the named route “_temp_unavailable” as such route does not exist.” at /var/www/cloud.supla.org/var/cache/prod/appProdProjectContainerUrlGenerator.php line 120 {“exception”:“[object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \“_temp_unavailable\” as such route does not exist. at /var/www/cloud.supla.org/var/cache/prod/appProdProjectContainerUrlGenerator.php:120)“} []

**Comment by fracz** [comment]
To jest zależne od @pkasprz i #139 bo obydwa wywołania dotyczą tworzenia konta. Prawdopodobnie problem zniknie sam przy przeniesieniu tych metod do API.
