### ISSUE TITLE
Implement "remove user" command

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#185]
https://github.com/SUPLA/supla-cloud/tree/master/src/SuplaBundle/Command

**Comment by fracz** [comment]
Try to set FKs so the items connected to the user are automatically deleted with `CASCADE DELETE`.

**Comment by przemyslawzygmunt** [comment]
DELETE CASCADE on supla_audit.FK_EFE348F4A76ED395 - added
