### ISSUE TITLE
Get rid of downgrade queries

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#190]
https://github.com/SUPLA/supla-cloud/blob/e1f51600f642de035d8c4908ae4151de84c27a4b/app/DoctrineMigrations/Version20171210105120.php#L20

**Comment by fracz** [comment]
We agreed to get rid of downgrade queries.

```php
public function down(Schema $schema) {
    $this->abortIf(true, 'There is no way back');
}
```
