### ISSUE TITLE
Set limits based on values from parameters.yml (default - no limit)

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#192]
https://github.com/SUPLA/supla-cloud/blob/f4bd906c93108858be14c69070066a7b6d8f9f51/src/SuplaBundle/Entity/User.php#L205

**Comment by fracz** [comment]
remember about adding this to docker's `.env` file and qnap wizard

**Comment by fracz** [comment]
Wont fix in favour of #424
