### ISSUE TITLE
Scheduler - advanced crontab input

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#200]
![google_play](https://user-images.githubusercontent.com/6603397/37663782-418ff9e2-2c5a-11e8-948e-bfc23a6d8eb8.png)

**Comment by fracz** [comment]
We could provide a simple crontab editor, like one on the https://crontab.guru/

This would solve most of the cases.

**Comment by MacManiac78** [comment]
Would be great if you could add this option in the cloud. Would make things easy.

**Comment by fracz** [comment]
Useful lib for cron to human conversion: https://www.npmjs.com/package/cronstrue

**Comment by MacManiac78** [comment]
Hello,

This is useless for me, because i can not use codes. I use genuine Supla software en cloud only.

Ben

Outlook voor Android downloaden

________________________________

**Comment by MacManiac78** [comment]
Oh hahaha.....    Good luck with your search and coding!
Thanks for the update too!
:-)


________________________________

**Comment by fracz** [comment]
Before introducing this feature, the cron-expression lib need to be upgraded: https://ctankersley.com/2017/10/12/cron-expression-update/

**Comment by MacManiac78** [comment]
very kind....


MONTHS....   no answer....   now...  CLOSED.


Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by fracz** [comment]
It has been implemented and released in v2.3.34

**Comment by fracz** [comment]
https://github.com/SUPLA/supla-cloud/releases/tag/v2.3.34
