### ISSUE TITLE
Can't save properties on mobile browser.

### ISSUE THREAD

**Issue by m4rcelpl** [SUPLA/supla-cloud#214]
Hi,
On Chrome, Opera, Firefox @ Android can't save option because back button is on the same place as save. 
![screenshot_20180408-111901](https://user-images.githubusercontent.com/13198386/38551418-6022ea94-3cb9-11e8-99df-59ceec7b1e24.jpg)

**Comment by przemyslawzygmunt** [comment]
Problem solved in the latest version
![image](https://user-images.githubusercontent.com/6603397/38551717-354c77bc-3cba-11e8-9558-ba7e964d2f62.png)
