### ISSUE TITLE
Add support for monostable switches

### ISSUE THREAD

**Issue by JedrekWie** [SUPLA/supla-cloud#242]
At this point I can't see any option to achieve monostable switch functionality. What I mean by this is to be able to control device which generates short impulse (on and immediately after off) which then is chained and processed by other automation components.

I have this use case where circulation pump is controlled by stair-switch keeping the pump running for certain amount of time and then switching it off. 

I would imagine that either/or you can:
1. categorize device as monostable switch
2. handle such device in scheduling module

**Comment by przemyslawzygmunt** [comment]
This functionality is implemented on the side of executive devices.
Example:
https://github.com/SUPLA/supla-espressif-esp/blob/82293898dfcf08323c6b6ed62cf93005efed27d3/src/include/board/wifisocket.c#L73

**Comment by JedrekWie** [comment]
Thank you @przemyslawzygmunt for prompt reply! Much appreciated!
I'm more of a high level developer and I'm not sure what kind of conclusions your answer leads me to.
At this point I'm running Zamel Supla ROW-01 which in general supports monostable switches but anyway persists ON/OFF status on each press/use. 
Is this a matter of device executive software rather than Supla Cloud feature? In other words - if Zamel would have implemented it's device in a different way I would be able to achieve what I'm aiming for?

**Comment by JedrekWie** [comment]
@przemyslawzygmunt I followed your suggestion yesterday and found those options in the device config. Correct me if I'm wrong but they affect only device behavior in response to external input.
What I was trying to achieve by opening this issue is to have similar functionality on the Supla software side so that you can use device like ROW-01 as it would not have been BISTABLE device, but rather MONOSTABLE.
I can achieve that with external monostable switch attached to the device but not really using Supla Cloud nor e.g. Android Application.
ROW-01 presents itself in the apps as a lightning bulb which can be either ON or OFF. In order to achieve monostable-like functionality you need to:
1. In the mobile app:
a) swipe left
b) tap ON
c) swipe right
d) tap OFF
2. In the Supla Cloud (Schedules)
a) define one schedule with ON action at xx:yy
b) define second schedule with OFF action at xx:zz, where zz = yy + 1 minute (smallest interval)

As you can see due to complexity this is not really user friendly...

I know that from the design perspective there can be many ways how to achieve this and I'm sure you could easily judge which way is the best, e.g. by letting define **device mode** - MONOSTABLE/BISTABLE you could:
1. In Cloud Schedules let define only on schedule type - ON_OFF
2. In mobile apps - present device as "bell" and enable only "swipe left -> ON" feature.

**Comment by przemyslawzygmunt** [comment]
Whether the device supports a monostable or bistable relay also depends on it. I think you mean the "channel function".

SUPLA_CHANNELFNC_ *
https://github.com/SUPLA/supla-core/blob/proto_v10/supla-common/proto.h#L260

"BUTTON", "BELL" function, etc. they will be implemented in the future.
