### ISSUE TITLE
Changing the procedure for determining the destination server address.

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#245]
During the procedure of creating a new user, retrieve the destination server address from the autodiscover server. Remove new_account_server_list parameter.
(Pass the client's IP address with the request.)

https://github.com/SUPLA/supla-cloud/blob/4d2ff25d4e0c05a4a92260fbc78dc5428abc2768/src/SuplaBundle/Supla/ServerList.php#L78

**Comment by fracz** [comment]
`GET /servers/email@domain.com?ip=1.2.3.4`

**Comment by przemyslawzygmunt** [comment]
GET /servers/new-account/email@domain.com?ip=1.2.3.4 

?

**Comment by przemyslawzygmunt** [comment]
GET /servers/new-account-destination/email@domain.com?ip=1.2.3.4

?

**Comment by fracz** [comment]
whatever for me, `GET /new-account-servers/email@domain.com?ip=1234` would be more restful. If the e-mail address is not needed (IP only), then we can omit it, too `GET /new-account-servers/1.2.3.4`

**Comment by przemyslawzygmunt** [comment]
GET /new-account-server/1.2.3.4
