### ISSUE TITLE
Add an abstract measurement channel

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#258]
https://forum.supla.org/viewtopic.php?p=29302#p29302

**Comment by fracz** [comment]
Jednostkę, precyzję, czy mają się historia gromadzić, czy mają być dostępne wykresy. Jeśli tak to na jakich zasadach (tak jak dla termometrów czy tak jak dla liczników energii).

Czy int-y czy double, minimalna i maksymalna wartość.

Jak przekroczy min/,max to jak ma się system zachować.

**Comment by fracz** [comment]
Prefix, suffix
Mnożnik/dzielnik 
Jednostkę miary 
Dokładność 
Check czy gromadzić historię
Check określający czy wykresy maja być prezentowane tak jak w termometrach czyli jeden do jeden z tym co w  bazie 
Czy tak jak w licznikach energii czyli różnicowy 
delta pomiaru
