### ISSUE TITLE
Verify Target Cloud connection before auth redirection

### ISSUE THREAD

**Issue by fracz** [SUPLA/supla-cloud#269]
sprawdzanie poprawności połączenia przed przekierowaniem do Target Clouda

**Comment by przemyslawzygmunt** [comment]
To samo powinno dotyczyć odświeżania...
W przypadku gdy klient wyśle żądanie odświerzenia tokena to broker też powinien sprawdzić czy terget jest dostępny i czy ma poprawny certyfikat. Jeżeli nie to powinien odpowiedzieć jakimś błędem 502 albo 503
