### ISSUE TITLE
Not existing input parameter for POST /locations

### ISSUE THREAD

**Issue by magx2** [SUPLA/supla-cloud#287]
As I assume this endpoint should create and return `Location`

```yaml
    post:
      summary: Create a new location
      operationId: createLocation
      tags:
        - Locations
      responses:
        '201':
          description: Newely created location with automatic name
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
```
The problem is that it doe not have `requestBody`

**Comment by fracz** [comment]
Every POST request to this endpoint results in creation of new location with random password and autor-generated name. There is no request body, so the docs says true. Access IDs have very similar behavior. These are one of the oldest Cloud endpoints. Although agree that they should accept same params, I don't see a real value in changing them.

**Comment by magx2** [comment]
OK I understand
