### ISSUE TITLE
ElectricityMeter - split functions

### ISSUE THREAD

**Issue by fracz** [SUPLA/supla-cloud#336]
IMPULSECOUNTER -> IMPULSE_ELECTRICITY_METER (305), IMPULSE_GAS_METER (320), IMPULSE_WATER_METER (330) (edited) 
ELECTRICITY_METER -> ELECTRICITY_METER (310)

305 is the new id. Data needs to be migrated.

After this change, a lot of code that depends on the channel type can be simplified.

**Comment by przemyslawzygmunt** [comment]
https://github.com/SUPLA/supla-core/issues/115
