### ISSUE TITLE
Add support for roller shutter with auto-calibration

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#346]
https://github.com/SUPLA/supla-core/issues/123

**Comment by fracz** [comment]
Jeśli kanał ma ustawioną flagę  https://github.com/SUPLA/supla-core/blob/develop/supla-common/proto.h#L397
To pola do ustawiania czasu otwarcia zamknięcia powinny być niewidoczne. Zamiast nich powinien pojawić się przycisk “Wymuś ponowną kalibrację”
