### ISSUE TITLE
Verify why the IP address in the GUI does not match the address in the database

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#349]
https://forum.supla.org/viewtopic.php?p=59245#p59245

**Comment by Goral64** [comment]
It only behaves like this on a 32 bit system.
On 64 bit it is correct.
Maybe you should change the storage of the IP address from integer to varchar?

**Comment by przemyslawzygmunt** [comment]
Keeping it as a varchar is a bad idea. It should be determined why the GUI reads this int incorrectly.

**Comment by fracz** [comment]
https://groups.google.com/forum/#!topic/doctrine-user/gdCG5MoByD4
