### ISSUE TITLE
Mail sensor icon shows opposite state compared to mobile app

### ISSUE THREAD

**Issue by klew** [SUPLA/supla-cloud#354]
When mobile app shows icon with envelop in box, cloud shows empty box. And vice versa.

**Comment by fracz** [comment]
Are you sure? We had such problems in the future (https://github.com/SUPLA/supla-cloud/commit/25d25a7968c32ddf9edbf7d33ea77608325b5e91) but it was a result of putting wrong icons in wrong files. Mail sensor seems to be ok: https://github.com/SUPLA/supla-cloud/blob/master/web/assets/img/functions/240-closed.svg

@michaelevening can you confirm?

**Comment by klew** [comment]
Yes, I'm sure.
On value "1" cloud shows empty box, and app shows envelop in the box.
