### ISSUE TITLE
I can't connect supla.local

### ISSUE THREAD

**Issue by lambinhchi147** [SUPLA/supla-cloud#366]
Hi.
I have followed your tutorial.
this is file parameters.yml
This file is a "template" of what your parameters.yml file should look like
parameters:
  database_driver: pdo_mysql
  database_host: 127.0.0.1
  database_port: ~
  database_name: supla
  database_user: root
  database_password: ~
  mailer_transport: smtp
  mailer_host: 127.0.0.1
  mailer_user: ~
  mailer_password: ~
  mailer_port: 465
  mailer_encryption: ssl
  mailer_from: ~
  admin_email: ~
  supla_server: supla.local
  supla_require_regulations_acceptance: false
  supla_require_cookie_policy_acceptance: false
  brute_force_auth_prevention_enabled: true
  recaptcha_enabled: false
  recaptcha_site_key: ~
  recaptcha_secret: ~
  use_webpack_dev_server: true
  locale: en
  supla_protocol: http
  A secret key that's used to generate certain security-related tokens
  secret: ThisTokenIsNotSoSecretChangeIt
  cors_allow_origin_regex: []
![image](https://user-images.githubusercontent.com/63535177/79063638-00b19780-7ccd-11ea-9ed8-e6ffafed79a1.png)

**Comment by fracz** [comment]
Look like you are almost there.

Have you defined a VHost representing a `supla.local` virtual domain? Have you added a `hosts` entry?

Steps 10 and 11 from https://github.com/SUPLA/supla-cloud/blob/master/Development.md

**Comment by lambinhchi147** [comment]
![image](https://user-images.githubusercontent.com/63535177/79076941-c6291880-7d27-11ea-847d-44bdce78922f.png)

**Comment by fracz** [comment]
Hosts entry should not contain the protocol, just the name.

```
127.0.0.1   supla.local
```

**Comment by lambinhchi147** [comment]
Thank you. 
I have access to supla.local and there are some errors
![image](https://user-images.githubusercontent.com/63535177/79231552-72860e80-7e90-11ea-8d80-73fdc5bdbc1a.png)
![image](https://user-images.githubusercontent.com/63535177/79231570-7ade4980-7e90-11ea-953d-b9b1c0609634.png)
![image](https://user-images.githubusercontent.com/63535177/79231610-89c4fc00-7e90-11ea-8763-c61ef3a8c73d.png)

**Comment by fracz** [comment]
Are you sure you have PHP 7+ and installed the dependencies with `composer install`?

**Comment by lambinhchi147** [comment]
I guess so. I will delete it and try again. thanks.
