### ISSUE TITLE
Opening the valve closed manually

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#368]
- If opening from the GUI level then the user should answer the question "The valve has been closed in manual or radio mode. Before you open it, make sure it has not been closed due to flooding. To turn off the warning, open the valve manually. Are you sure you want to open it?! ".

- Opening valves closed manually with RestAPI should not be available for applications other than Cloud GUI.

- The API should return information on whether the valve has been manually closed.

**Comment by fracz** [comment]
https://github.com/SUPLA/supla-android/blob/c8ac3b213c4488741982b0fffb077e248c6fd3f0/app/src/main/res/values-pl/strings.xml#L263

**Comment by fracz** [comment]
Supla Server communication:

Getting the open/close state:
`GET-CHAR-VALUE:1,1,1` -> `VALUE:1\n`

Getting the manual shut state:
`GET-VALVE-MANUAL-SHUT-VALUE:1,1,1` -> `VALUE:1\n`
