### ISSUE TITLE
Missing `ChannelType` for `ElectricityMeter`

### ISSUE THREAD

**Issue by magx2** [SUPLA/supla-cloud#378]
[ChannelType](https://app.swaggerhub.com/apis/supla/supla-cloud-api/2.3.0#/ChannelType) does not have `ELECTRICITYMETER` type.

**Comment by magx2** [comment]
Same for [ChannelFunctionEnumNames](https://app.swaggerhub.com/apis/supla/supla-cloud-api/2.3.0#/ChannelFunctionEnumNames)

**Comment by fracz** [comment]
https://github.com/SUPLA/supla-cloud/issues/503
