### ISSUE TITLE
Can't contact private cloud from skill Amazon

### ISSUE THREAD

**Issue by micdj** [SUPLA/supla-cloud#436]
when I add skill with private cloud, it say can't find server on www.supla-cloud.it , but it works correctly with correct SSL certificate, I can't also register on https://cloud.supla.org/register-cloud 

Any ideas?

Thank you

**Comment by przemyslawzygmunt** [comment]
Any screenshots ?

**Comment by micdj** [comment]
![image](https://user-images.githubusercontent.com/65829414/109416622-b3f7ad80-79bf-11eb-9c7b-8c2c7d65abdb.png)

**Comment by micdj** [comment]
![image](https://user-images.githubusercontent.com/65829414/109416677-fcaf6680-79bf-11eb-826f-488b05cc9e91.png)

**Comment by przemyslawzygmunt** [comment]
Please use a different domain name that does not contain "supla" in the phrase. The domain used may mislead our clients in Italy, who may consider it a commercial part of our project. The Supla name and logo are legally protected.

**Comment by micdj** [comment]
ok, thank you i Try, i don't know that I can't use the name supla in project

**Comment by przemyslawzygmunt** [comment]
The error is related to something else, but we will verify it only after you change the domain address.

**Comment by micdj** [comment]
ok, I'm changing

**Comment by micdj** [comment]
ok now domain is switchdomo.eu, same error

**Comment by micdj** [comment]
![image](https://user-images.githubusercontent.com/65829414/109420245-a9deaa80-79d1-11eb-9b32-ff1db0b85681.png)

**Comment by przemyslawzygmunt** [comment]
First you need to properly register your instance at https://cloud.supla.org/register-cloud

I pre-checked that our servers were unable to verify your certificate.
Remember to install intermediate certificates

 openssl s_client -connect switchdomo.eu:443 -servername switchdomo.eu
CONNECTED(00000003)
depth=0 CN = switchdomo.eu
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = switchdomo.eu
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:/CN=switchdomo.eu
   i:/C=US/O=Let's Encrypt/CN=R3
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFIDCCBAigAwIBAgISBOaR8Y9/V9cLCm7vJpro7da9MA0GCSqGSIb3DQEBCwUA
MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
EwJSMzAeFw0yMTAyMjgxMjE2MTRaFw0yMTA1MjkxMjE2MTRaMBgxFjAUBgNVBAMT
DXN3aXRjaGRvbW8uZXUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDh
cSlLh+Pxz+l+fbo0CXMsfxtP2t72XRlPsvsLXpg0cuULzNmYYhVpSF/ayW0pnrYS
B80TZ8evrH/V+0/a/KrmOlOCEVLEgdJGXxo0xQY2XdB7dFV18E+Lq8z0W9XZmh41
zAcM/Bs5tCX7OqGZI0EDVtuGFq7oKJvKLOZ6u1gX/xsxuRPfxeB1rLIgthD7wlFc
b7vmL0g8I0OwS9VP37r6g3W0nP9HYwo/hFBd9xKVbGATegH1ncbhmjm9sYmORZbe
o87QNFG7c+ltkllsjie7b08J2Rp7JqeX2PNprTCW8zdmOtjemFbGN5XUJUr2auwb
FkPz9rSSfuEEEedr2Kh9AgMBAAGjggJIMIICRDAOBgNVHQ8BAf8EBAMCBaAwHQYD
VR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0O
BBYEFHKo2xBu1I15RoYtMk0r2I0oexTjMB8GA1UdIwQYMBaAFBQusxe3WFbLrlAJ
QOYfr52LFMLGMFUGCCsGAQUFBwEBBEkwRzAhBggrBgEFBQcwAYYVaHR0cDovL3Iz
Lm8ubGVuY3Iub3JnMCIGCCsGAQUFBzAChhZodHRwOi8vcjMuaS5sZW5jci5vcmcv
MBgGA1UdEQQRMA+CDXN3aXRjaGRvbW8uZXUwTAYDVR0gBEUwQzAIBgZngQwBAgEw
NwYLKwYBBAGC3xMBAQEwKDAmBggrBgEFBQcCARYaaHR0cDovL2Nwcy5sZXRzZW5j
cnlwdC5vcmcwggEEBgorBgEEAdZ5AgQCBIH1BIHyAPAAdgD2XJQv0XcwIhRUGAgw
lFaO400TGTO/3wwvIAvMTvFk4wAAAXfoyELyAAAEAwBHMEUCIC2POAd28u+UWznw
kKD6JwNUlDxZ6HQ1TuHqh31F1NRQAiEAg6Eg4tUzhgWjzVHf0vtlhHIkbxpEYiq0
zm2AdNiUVbgAdgBc3EOS/uarRUSxXprUVuYQN/vV+kfcoXOUsl7m9scOygAAAXfo
yENFAAAEAwBHMEUCIQD6IhrBJpYfIpA2FbTiSAMYIg+eHtlU0SthM7kKb33smgIg
VALE7QrYF1gNx9rRr0v5srFWos4DcQwp5KlMUbp2olYwDQYJKoZIhvcNAQELBQAD
ggEBAADLe+Qe85D3+XPvxInw6E02Qj+5feQwDEImxZRx+U6yLKk+SRUBEI3A/xxY
R7AZ8temgeg0gWi/ijEVj2ffhmDB/sEigTBHC+bu5qc3DCq3r7ygAr5Zuolg/jXC
OoELjKoEAXQl0XegREGEGJIyWG9UTvQlX7QkgiTcqgFOi1+Fv2NkB9jadTQ5u4Tm
9rL3cdbw4LZsUdyEpNzYrOxlsapw17wsuF4nONcegrT6KpSaBumybfQKo9Svw+e6
ThYoMR5jx7kl2BqBjXvI/pVL/E4kYGrnRmx6mFZKz6XO4B1aXqgIV8oIjWUxgNAd
Izx6v8SVNeWVBkcAVSGolHZTPQg=
-----END CERTIFICATE-----
subject=/CN=switchdomo.eu
issuer=/C=US/O=Let's Encrypt/CN=R3
---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 2018 bytes and written 324 bytes
Verification error: unable to verify the first certificate
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 0A17806A697FD0601F231FEC250A14D95C89839D54DF7DD308478FD2AB0CEE9B
    Session-ID-ctx: 
    Master-Key: 26DC0970FACBBE6855C013BD1F7CD3057C6018ADCDDF5FD8CBD0702ADCE87527DF3FCB4E70AC824EBAD3755EF4AF9229
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    0000 - e3 0e 88 a8 4f 06 53 43-d3 4f 12 e7 cb 13 e6 f0   ....O.SC.O......
    0010 - 93 59 93 61 9b 9f c2 6b-5e 3d 4b 6b ec 03 06 79   .Y.a...k^=Kk...y
    0020 - 64 df 0a 2e c9 54 31 c4-93 d8 bd 01 93 c6 22 9f   d....T1.......".
    0030 - bf fa d0 23 3b 7c 23 b7-be 01 a1 11 2d dc 07 31   ...#;|#.....-..1
    0040 - 8a 2c 8c b4 5d 51 aa b4-fb d3 74 46 62 b0 ff 79   .,..]Q....tFb..y
    0050 - 96 97 99 aa fd ed 33 49-04 b1 fe 7b 0d 9e cd 4f   ......3I...{...O
    0060 - 44 c3 df 8f 72 92 3b ee-87 44 f9 b4 ff ab 71 f6   D...r.;..D....q.
    0070 - f5 d9 9b 74 9d d8 27 c8-b1 50 78 6d 00 a3 0e ce   ...t..'..Pxm....
    0080 - 16 88 69 f9 1f cb 43 ad-ac f6 f3 af 8c 5b f8 b0   ..i...C......[..
    0090 - 6c b3 b1 98 7b 1e 08 08-fd 0f 25 3c e4 7d 8c 16   l...{.....%<.}..
    00a0 - a0 3f 1f f6 78 c6 5a 68-80 5d 90 b2 c9 eb e1 b7   .?..x.Zh.]......
    00b0 - f6 62 ba 2a ad 66 58 fb-f8 86 e3 a9 c1 df 65 21   .b.*.fX.......e!
    00c0 - 6a 41 52 4e 35 2a 4a 2b-97 93 d3 34 f0 72 69 11   jARN5*J+...4.ri.

    Start Time: 1614532079
    Timeout   : 7200 (sec)
    Verify return code: 21 (unable to verify the first certificate)
    Extended master secret: no

**Comment by micdj** [comment]
Good news!! I used intermediate certificate and now it work well with Alexa. 

I want to ask another thing, is it normal that on app if I use a mail registered on my private cloud, it don't link to my server address as for mail registered on cloud.Supla.org, server form stay blank. 



![Screenshot_2021-02-28-23-03-12-669_org supla android](https://user-images.githubusercontent.com/65829414/109435132-33659b00-7a19-11eb-9a69-0a02c562b0fe.jpg)
![Screenshot_2021-02-28-23-03-09-005_org supla android](https://user-images.githubusercontent.com/65829414/109435133-3496c800-7a19-11eb-8a55-eed4c57fb7ea.jpg)

**Comment by przemyslawzygmunt** [comment]
We apologize for this inconvenience. The settings will be rebuilt. Before that, you must follow the procedure below to use an email address with a private instance.


1. Deselect Advanced
2. Enter the email address
3. Select Advanced
4. Enter the server address
5. Deselect Advanced
6. Tap OK
