### ISSUE TITLE
Do not show charts for data that is not collected.

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#450]
https://github.com/SUPLA/supla-core/blob/master/supla-common/proto.h#L455
https://github.com/SUPLA/supla-core/blob/master/supla-common/proto.h#L1167

The problem is that the cloud does not know what data is collected. This could determine if a given field in supla_em_log is not NULL

**Comment by fracz** [comment]
Cloud will know after #493 what measurements are supported

**Comment by fracz** [comment]
@przemyslawzygmunt czy wartość `countersAvailable` wprowadzona w #493 będzie dostępna od razu dla wszystkich kanałów z typem EM? Chciałbym użyć tej wartości do ukrycia niewspieranych wykresów na stronie szczegółów liczników energii, tylko że jak ta wartość będzie pusta to wtedy wykresy nie pojawią się w ogóle.

**Comment by przemyslawzygmunt** [comment]
Tak ale clounterAvailable uaktualni się dopiero przy połączeniu licznika z serwerem. Dopóki będzie offline to porperties nie będą ustawione.

**Comment by fracz** [comment]
ok, w takim razie zachowam obecną funkcjonalność jeśli wartości nie ma, i dostosuję wyświetlanie jeśli wartość będzie
