### ISSUE TITLE
Add a button to reset the counters

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#456]
If a given channel has the following flag turned on
https://github.com/SUPLA/supla-core/blob/ffa56e4579812c50ca15202c698d0c1d363a0258/supla-common/proto.h#L458

the "Reset counters" button should be omitted in the history of measurements.

**Comment by fracz** [comment]
RESET-COUNTERS:UserId,DeviceId,ChannelId
22:00
Rezultat
22:00
OK:ChannelId
