### ISSUE TITLE
Visual glitches v2.3.32 

### ISSUE THREAD

**Issue by fracz** [SUPLA/supla-cloud#459]
https://forum.supla.org/viewtopic.php?p=100650#p100650

**Comment by jaku2019** [comment]
Hello,
In Supla Cloud v2.3.33 I still see a problem with "Create New Access Identifier" button on my mobile device. It's too wide for my 5.00" display, so I can swipe the site left and right. The problem occurs in the polish version (in english one the sign on the button seems to be short enough). I don't know if this problem occurs on bigger smartphones (5.00" is pretty small for 2021 phone).
Regards
Jakub
![Access_ID_problem](https://user-images.githubusercontent.com/55255300/131257178-1df296f1-7f94-4697-9313-3eb2f114fee7.png)

**Comment by fracz** [comment]
@jaku2019 the problem you described here should be fixed in 2.3.34

**Comment by jaku2019** [comment]
@fracz Indeed. Thank you.
![Access_ID_solution](https://user-images.githubusercontent.com/55255300/131407811-6991803b-fd40-44ad-a2ae-4342f61adb28.png)
