### ISSUE TITLE
Add the "Recalibration" button if the SUPLA_CHANNEL_FLAG_CALCFG_RECALIBRATE flag is set

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#464]
https://github.com/SUPLA/supla-core/blob/develop/supla-common/proto.h#L458

Applies to SUPLA_CHANNELFNC_CONTROLLINGTHEROLLERSHUTTER and SUPLA_CHANNELFNC_CONTROLLINGTHEROOFWINDOW functions

**Comment by fracz** [comment]
`RECALIBRATE:user_id,iodev_id,channel_id`

**Comment by fracz** [comment]
Jeśli kanał rolet ma ją ustawioną to w UI przy ustawianiu czasu powinien być wybór “Auto/Manual” przy wyborze manual powinna być możliwość ustawienia czasu jak dotychczas, ale czas musi być > 0. Ustawienie “Auto” powinno ustawiać czas na 0.

**Comment by fracz** [comment]
https://github.com/SUPLA/supla-cloud/issues/449

**Comment by fracz** [comment]
W aplikacji komunikat po naciśnięciu przycisku jest taki:
11:56
Czy na pewno chcesz rozpocząć kalibrację ?
