### ISSUE TITLE
Visual glitches v2.3.33

### ISSUE THREAD

**Issue by jaku2019** [SUPLA/supla-cloud#468]
Hello,
I found one visual glitch that occurs when trying to add first device to channel group. The badge is being troncated by the overlay.
![blad](https://user-images.githubusercontent.com/55255300/129888660-dc5694a3-f108-4fcb-a129-883fa8ca3a77.PNG)

https://forum.supla.org/viewtopic.php?f=20&t=9069

**Comment by fracz** [comment]
Thank you!
