### ISSUE TITLE
"BŁĄD" - bold letters "Ł" and "Ą"

### ISSUE THREAD

**Issue by jaku2019** [SUPLA/supla-cloud#472]
Hello,
last time, when I was looking for an update for Cloud (from v2.3.33 to v2.3.34) I saw notification "ERROR [...]". In Polish version of this information Polish letters are bold.
Regards,
Jakub

PS. I added a comment to the closed issue: https://github.com/SUPLA/supla-cloud/issues/459#issuecomment-907828725
![blad](https://user-images.githubusercontent.com/55255300/131397451-5e3b9a8c-56aa-4a24-b6c3-4c769666823f.png)

**Comment by fracz** [comment]
Thank you, will take a look at it

**Comment by fracz** [comment]
You must have hit the short period when the server was down and therefore - could not load the font correctly. These letters seems to be working fine if the application was loaded fully.

![image](https://user-images.githubusercontent.com/3918865/133858435-adea9468-c638-482f-8877-a809b634e7ff.png)

Feel free to reopen if you see the problem again.

Thank you.
