### ISSUE TITLE
Add buttons are not aligned to the center (mobile devices)

### ISSUE THREAD

**Issue by jaku2019** [SUPLA/supla-cloud#477]
Hello,
in the newest Cloud v2.3.34 buttons for adding (for example devices, locations, etc.) aren't centered - they're aligned to the left side of the screen. Only "Create New Access Identifier" button is centered.
Regards,
Jakub
![homescreen](https://user-images.githubusercontent.com/55255300/132109165-6269f1be-c686-4105-ada9-a5f90fd302d8.png)
![locations](https://user-images.githubusercontent.com/55255300/132109167-1d568820-47b6-48cc-948f-9364ff3313f5.png)

**Comment by fracz** [comment]
Fixed in v2.3.36
