### ISSUE TITLE
Spacing between buttons v2.3.34

### ISSUE THREAD

**Issue by jaku2019** [SUPLA/supla-cloud#481]
Hello,
I found some places in the Cloud, where buttons seem to be to close to each other. Photos in the attachment.
Regards,
Jakub
![spacing_1](https://user-images.githubusercontent.com/55255300/133885737-1803e9b9-6815-4bf4-8beb-1a70dcc73e6a.PNG)
![spacing_2](https://user-images.githubusercontent.com/55255300/133885738-4de40f5a-b034-4c67-b413-b171a0b78e80.PNG)
![spacing_3](https://user-images.githubusercontent.com/55255300/133885739-e9ff977b-76e1-4bf7-bd50-f1f7fa214ffc.PNG)

**Comment by fracz** [comment]
Fixed, will be realeased in the next version, thank you!
