### ISSUE TITLE
Setting number of retries for OPEN/CLOSE actions

### ISSUE THREAD

**Issue by fracz** [SUPLA/supla-cloud#492]
W bramach są nowe akcje “OPEN” i “CLOSE”. One wymagają czujnika otwarcia i są wykorzystywane przez GH. Po 60 sekundach sprawdzają stan i jeśli cel jest nieosiągnięty to ponawiają próbę. Dla niektórych osób to jest problem i chcą zmniejszyć liczbę powtórzeń.

**Comment by fracz** [comment]
Albo inaczej. Zamiast pisać o ponowieniach to daj Ilość prób otwarcia/zamknięcia i daj “1

daj 1-5

5 jest domyślnie

**Comment by przemyslawzygmunt** [comment]
The content of the balloon needs to be refined
