### ISSUE TITLE
Add a recording of too low/high voltage.

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#511]

**Comment by fracz** [comment]
@przemyslawzygmunt czy możesz podsumować wymagania dotyczące tego zadania?

**Comment by fracz** [comment]
Na chwilę obecną każdy pomiar przekazuję do dedykowanej klasy, która na bieżąco liczy wartość minimalną, maksymalną, średnią, zlicza ilość próbek, ile razy napięcie wyszło poza górny próg, ile razy zeszło poniżej dolnego progu, liczy jak długo ciągiem napięcie utrzymywało się powyżej górnego progu i to samo poniżej dolnego. Zlicza również jak długo "łącznie" utrzymywało się napięcie powyżej progu i poniżej. Odczytuję te wartości co 10 min i je wszystkie zeruje. Mam też czas w sekundach ile trwało zbieranie paczki danych (zwykle powinno być ~10min). Zmienne: total_count int, total_sec int, min double, max double, avg double, lower_counter int, upper_counter int, total_sec_above int, total_sec_below int, max_sec_above int, max_sec_below. Wszystkie te dane mogę zapisać jeśli upper_counter > 0 lub lower_counter > 0. Użytkownikowi można prezentować te dane w postaci wykresu świecowego gdzie po dotknięciu można wyświetlić szczegóły w postaci wszystkich wyżej wymienionych danych. Pod wykresem można dać tabelkę z danymi źródłowymi.

**Comment by fracz** [comment]
W configu: `lowerVoltageThreshold` i `upperVoltageThreshold`

**Comment by fracz** [comment]
https://github.com/SUPLA/supla-core/issues/166
