### ISSUE TITLE
Add the option to define in what hours and days a given access ID is available

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#514]
https://forum.supla.org/viewtopic.php?p=116466#p116466
https://github.com/SUPLA/supla-core/issues/264

**Comment by fracz** [comment]
![image](https://user-images.githubusercontent.com/3918865/157994511-6455f079-961b-46a3-97a3-f05eddda17d9.png)

**Comment by przemyslawzygmunt** [comment]
![Image](https://user-images.githubusercontent.com/6603397/180624289-c1a64750-16c8-4b76-9f85-2e20b5e3a01f.png)

Enabling / disabling active hours clears access identifiers for clients. It shouldn't work that way.

**Comment by przemyslawzygmunt** [comment]
The Fron was not refreshed which gave this effect.
