### ISSUE TITLE
Simple logic for electricity meter 

### ISSUE THREAD

**Issue by fracz** [SUPLA/supla-cloud#515]
Chodzi o wyłączanie i włączanie urządzeń w zależności od poboru. Może w 2.3.37 wprowadzimy proste warunku w ustawieniach np. MEW-a. Załącz kanał X jeśli konsumpcja spadnie do Y, wyłącz grupę Q jeśli konsumpcja wzrośnie powyżej Z ? Taka namiastka logiki ale na tyle prosta by nikt nie musiał skryptów pisać.

**Comment by przemyslawzygmunt** [comment]
Załączanie/wyłączanie w zależności od mocy/napięcia. 
https://github.com/SUPLA/supla-core/issues/335

**Comment by przemyslawzygmunt** [comment]
https://github.com/SUPLA/supla-cloud/issues/702
