### ISSUE TITLE
Missing translations in meters form

### ISSUE THREAD

**Issue by klew** [SUPLA/supla-cloud#528]
Selecting currency default value is not translated - it shows "wybierz walutę".
Also when I click on it, there is "szukaj" placeholder which is not translated.

![Clipboard - 9 lutego 2022 12_49](https://user-images.githubusercontent.com/205610/153296768-4e9cf706-808a-462f-87f6-7aa288a6568a.png)

**Comment by przemyslawzygmunt** [comment]
This placeholder has a translation. You just have to refresh the page after changing the language (F5)

**Comment by przemyslawzygmunt** [comment]
https://github.com/SUPLA/supla-cloud/issues/531
