### ISSUE TITLE
"Added value" - introduce the possibility of setting a negative value. Applies to energy meters and pulse counters.

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#536]

**Comment by fracz** [comment]
Czy nie lepiej w takim razie zapytać użytkownika o "aktualny stan licznika ze ściany"? Cloud sobie przeliczy i ustawi odpowiednią wartość początkową by się zgadzało.

**Comment by fracz** [comment]
@przemyslawzygmunt
