### ISSUE TITLE
Cannot change channel group name v2.3.37

### ISSUE THREAD

**Issue by jaku2019** [SUPLA/supla-cloud#540]

**Comment by fracz** [comment]
Seems to be working. Can you provide more details, please?

**Comment by jaku2019** [comment]
I didn't see that the field "caption" is interactive. Maybe you could make the green border visible constantly?

...but I can't change the name from the app. It's probably app's issue. If so, could you please move this thread to suitable place?
Regards,
Jakub

PS. What's the language rule on Supla's GitHub?

**Comment by fracz** [comment]
Whatever we can understand :-)

**Comment by fracz** [comment]
I have created an issue in supla-android https://github.com/SUPLA/supla-android/issues/304

Nevertheless, I'm not closing this issue yet. Will try to improve the design.
