### ISSUE TITLE
Are Registered and Last access filters needful?

### ISSUE THREAD

**Issue by jaku2019** [SUPLA/supla-cloud#541]
Hello,
do we need _Registered_ and _Last access_ filters in the device menu?
![issue](https://user-images.githubusercontent.com/55255300/157129214-fdb5a339-a5b4-42a0-b3de-19f393efc114.PNG)

As far as I know, the individual channels can't register separately nor disconnect separately from the Cloud if they belong to one device.
So... do we really need those filters there?
Best regards,
Jakub

**Comment by fracz** [comment]
Fixed, thank you.
