### ISSUE TITLE
Add "dawn" and "twilight" options for schedules

### ISSUE THREAD

**Issue by klew** [SUPLA/supla-cloud#547]

**Comment by fracz** [comment]
O co chodzi?

**Comment by klew** [comment]
Harmonogramy mają opcję uruchamiania przed/po wschodzie i zachodzie słońca.
W tym issue chodzi o dodanie analogicznej funkcji z ustawieniem przed/po świcie/zmierzchu

**Comment by klew** [comment]
to chyba byłby zbędny bajer. Zamykam
