### ISSUE TITLE
Add support for GET-SCENE-SUMMARY

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#556]

**Comment by przemyslawzygmunt** [comment]
Call Result.
SUMMARY:%SceneId,%InitiatorType,%InitiatorId,%InitiatorName_Base64,%MillisecondsFromStart,%MillisecondsToEnd

InitiatorTypes:
0 - Unknown
1 - Device
2 - Client / Smartphone 
3 - IPC (Cloud, Schedule)
4 - MQTT
5 - AmazonAlexa
6 - GoogleHome
7 - ActionTrigger
8 - Scene

**Comment by fracz** [comment]
Zrobione w v22.07
