### ISSUE TITLE
OAuth authorization - add a clear warning that the application is accessing your email address.

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#558]

**Comment by przemyslawzygmunt** [comment]
"Adres e-mail Użytkownika zostanie udostępniony do Aplikacji {APP_NAME}. Czy pozwolić na dostęp?”

**Comment by fracz** [comment]
![Image](https://user-images.githubusercontent.com/3918865/173796512-15c2e176-924b-4f97-bece-decb92b9e0fb.png)

**Comment by przemyslawzygmunt** [comment]
Zaproponowany komunikat pochodzi od prawnika
