### ISSUE TITLE
cloud sceny - zmiana nazwy scen nie jest odzwierciedlona na liście scen do uruchomienia w ramach sceny

### ISSUE THREAD

**Issue by fracz** [SUPLA/supla-cloud#573]
Gdy zmienię nazwę sceny, a następnie próbuję ją wybrać do uruchomienia z innej sceny, to lista nie ma zaktualizowanej nazwy (nie przeładowuje się)

![Image](https://user-images.githubusercontent.com/205610/180137242-9daaae54-876f-4d4e-af6c-93e65c813725.png)

**Comment by fracz** [comment]
To znaczy, że lista załadowała się przed zmianą. Tak to działa dla wszystkich elementów.

**Comment by klew** [comment]
Ale mogę nawet przełączać się na inne sceny i ta lista nadal się nie przeładowuje.
