### ISSUE TITLE
Scenes in a scene - add the option to specify whether the delay is to be counted from the beginning of the scene or from its end.

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#576]

**Comment by fracz** [comment]
> Czy przy tym tasku https://github.com/SUPLA/supla-cloud/issues/576 możesz samodzielnie przeliczać opóźnienie i zapysywać w bazie ? W bazie byłyby dwie wartości. Pierwsza to ta, którą wpisał użytkownik, a druga przeliczona. Ta przeliczona byłaby równa temu co użytkownik ustawił w przypadku gdy wybrano opóźnienie liczone od czasu rozpoczęcia sceny podrzędniej. Gdy wybrano opóźnienie liczone od momentu zakończenia sceny to wartość przeliczona uwzględniałaby czas wprowadzony przez użytkownika + czas sceny. Jeśli wartość przeliczona to byłaby supla_scene_[operation.delay](https://operation.delay/)_ms, a supla_scene_operation.user_delay_ms to wtedy po stronie serwera nie muszę nic więcej robić. supla_scene_operation.user_delay_ms to byłoby nowe pole w bazie.
