### ISSUE TITLE
Register private cloud - link

### ISSUE THREAD

**Issue by jaku2019** [SUPLA/supla-cloud#578]
It would be nice to have a button that redirects to that website (https://cloud.supla.org/register-cloud) somewhere. Not particularly in the cloud, but maybe somewhere on the https://supla.org website?

**Comment by fracz** [comment]
@przemyslawzygmunt ?

**Comment by Goral64** [comment]
@fracz @przemyslawzygmunt mogę to dodać tutaj dla lokalnych serwerów.
![register_server](https://user-images.githubusercontent.com/4144852/182940641-3151a141-eeb5-4503-a42a-291f38389f29.jpg)

**Comment by fracz** [comment]
Moim zdaniem ten link powinien być na stronie supla.org, a nie w cloudzie. Jeśli będzie w cloudzie to wyświetli się on wszystkim userom korzystającym z tej instancji - a niekoniecznie są oni jej "administratorami".

**Comment by Goral64** [comment]
Można to dodatkowo sparametryzować, aby tylko administrator to widział. Gdyby jeszcze było powiązane z informacją czy instancja jest zarejestrowana czy nie, to już w ogóle byłoby super. Oczywiście w takim razie trzeba by znaleźć lepsze miejsce dla takiego linka.

**Comment by fracz** [comment]
@przemyslawzygmunt jakie jest Twoje zdanie? Można ten link dać też na stronie logowania, który wyświetli się tylko w brokerach oraz w instancjach, które nie są zarejestrowane.

**Comment by fracz** [comment]
Frontend now can determine if the Cloud is registered with `this.$frontendConfig.isCloudRegistered`.

The link to the Cloud registration page is displayed in the login page if the instance is not registered.

![image](https://user-images.githubusercontent.com/3918865/193919056-d91bbaa2-6159-40d7-bbb1-a259f6543b16.png)
