### ISSUE TITLE
Apps catalolg on private instances

### ISSUE THREAD

**Issue by jaku2019** [SUPLA/supla-cloud#604]
"Apps" button redirects to cloud.supla.org/apps even on private instances.

https://forum.supla.org/viewtopic.php?p=127146#p127146
https://forum.supla.org/viewtopic.php?p=127149#p127149

**Comment by Goral64** [comment]
mogę zrobić

**Comment by fracz** [comment]
IMO link powinien kierować tam gdzie kieruje. Lista aplikacji tam zawsze jest aktualna. Jeśli instancja prywatna jest niezarejestorwana - katalogu w ogóle nie wyświetli.

**Comment by Goral64** [comment]
W sumie dobrze byłoby wysłać instancji lokalnej informację, czy jest zarejestrowana czy nie...

**Comment by fracz** [comment]
Podobny problem: #578

**Comment by fracz** [comment]
W tym zadaniu nadal uważam, że link prowadzi w dobre miejsce (do oficjalnej, aktualnej listy). Jeśli macie mocne argumenty przeciw to proszę o reopen z komentarzem.
