### ISSUE TITLE
Add the "Sensor opening - canceling opening / closing tasks" option - you must also add an appropriate description and warning.

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#611]

**Comment by przemyslawzygmunt** [comment]
https://github.com/SUPLA/supla-core/issues/306

**Comment by fracz** [comment]
@przemyslawzygmunt potrzebuję więcej info

**Comment by fracz** [comment]
To to? https://forum.supla.org/viewtopic.php?p=127680#p127680

Jeśli tak to nadal potrzebuję dwa zdania od Ciebie jak to ma działać.

**Comment by przemyslawzygmunt** [comment]
Przy czujniku można dać opcję "Przerwij ponawianie" i w (i) info "Po tym jak zlecisz otwarcie lub zamknięcie bramy, system podejmie próbę jej zamknięcia/otwarcia i poczeka 60 sekund aby sprawdzić, czy brama osiągnęła pożądany stan. Jeśli w między czasie czujnik przejdzie w stan zgodny ze stanem bramy jaki ma być osiągnięty to przy włączonej opcji „Przerwij ponawianie” system przerwie oczekiwanie na weryfikację stanu bramy i nie będzie ponawiać próby otwarcia/zamknięcia.

**Comment by fracz** [comment]
W user_config przy czujniku możemy dodać opcję "retryInterrupt: true"

**Comment by przemyslawzygmunt** [comment]
Dotyczy: SUPLA_CHANNELFNC_OPENINGSENSOR_GARAGEDOOR i SUPLA_CHANNELFNC_OPENINGSENSOR_GATE.

**Comment by fracz** [comment]
W GUI ja bym dałą opcję "Ponawiaj", "Retry", która jest domyślnie włączona. "Przerwij ponawianie" w GUI to jakiś WTF. I czy to na pewno ma być opcja przy czuniku, a nie przy bramie?

**Comment by klew** [comment]
"ponawiaj" brzmi zbyt podobnie do istniejącej opcji "liczba prób otwarcia". W tej opcji nie chodzi o to czy mamy ponawiać czy nie, tylko o to czy sprawdzenie czy został osiągnięty stan docelowy, ma się odbywać na bieżąco, czy po 60s od wykonania akcji. 
Może coś w stylu "weryfikacja wykonania polecenia" z opcjami "po 60s", "ciągła"?
Ten parametr powinien być przy kanale bramy, a nie przy czujniku.

**Comment by przemyslawzygmunt** [comment]
Ta opcja powoduje anulowanie wszystkich zadań  zamknięcia/otwarcia, które są zgodne z aktualnym stanem czujnika jeśli nastąpiła zmiana stanu. Ponadto ta opcja jest przy czujniku, a nie przy kanale sterującym.

**Comment by fracz** [comment]
Ustawienie dla GATE i GARAGE_DOOR

**Comment by fracz** [comment]
![image](https://user-images.githubusercontent.com/3918865/193572269-1a74d3c0-75b8-4975-995a-100732d05858.png)
