### ISSUE TITLE
UI bugs

### ISSUE THREAD

**Issue by jaku2019** [SUPLA/supla-cloud#621]
Bugs from the screenshot are present in Cloud v22.07.

The first one is visible both on mobile and desktop browser (it's about the AT icon in the corner)...
![AT_UI](https://user-images.githubusercontent.com/55255300/189532174-1ca05f6b-ce7f-472b-88dd-3708203cf3aa.PNG)

whereas the second one is mobile-only.
![AT_UI-2 (Medium)](https://user-images.githubusercontent.com/55255300/189532362-adc93976-bc72-4429-b346-eec3fa2fff96.png)

Additionaly I found it very annoying that after entering _chanel details_ on mobile, the page goes to the end. For me it would be more intuitive, if - after entering _channel details_ - the top of the page would be presented.

**Comment by fracz** [comment]
Thank you for your suggestions. All problems have been fixed and will be live in the upcoming release.
