### ISSUE TITLE
When saving a channel that belongs to a device with the SUPLA_DEVICE_FLAG_SLEEP_MODE_ENABLED flag set (https://github.com/SUPLA/supla-core/blob/develop/supla-common/proto.h#L4890). You should display a message informing that this device can currently sleep, which means that the saved changes will be applied only after it is woken up.

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#622]

**Comment by fracz** [comment]
When saving a channel that belongs to a device with the SUPLA_DEVICE_FLAG_SLEEP_MODE_ENABLED flag set (https://github.com/SUPLA/supla-core/blob/develop/supla-common/proto.h#L4890). You should display a message informing that this device can currently sleep, which means that the saved changes will be applied only after it is woken up.

**Comment by fracz** [comment]
![image](https://user-images.githubusercontent.com/3918865/193477069-ecde8764-51d0-482a-9798-10aa7896fc52.png)
