### ISSUE TITLE
If the "Switch device to configuration mode" button is pressed and the device has the SUPLA_DEVICE_FLAG_SLEEP_MODE_ENABLED flag set (https://github.com/SUPLA/supla-core/blob/develop/supla-common/proto.h#L4890) then it should be displayed a message stating that this device is currently sleeping, which means it will go into configuration mode at the next wake-up.

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#623]

**Comment by fracz** [comment]
If the "Switch device to configuration mode" button is pressed and the device has the SUPLA_DEVICE_FLAG_SLEEP_MODE_ENABLED flag set (https://github.com/SUPLA/supla-core/blob/develop/supla-common/proto.h#L4890) then it should be displayed a message stating that this device is currently sleeping, which means it will go into configuration mode at the next wake-up.

**Comment by fracz** [comment]
"Urządzenie może aktualnie pracować w trybie uśpienia. Zostanie przełączone w tryb konfiguracji zaraz po wybudzeniu".

**Comment by fracz** [comment]
![Image](https://user-images.githubusercontent.com/3918865/193478149-8f315e29-9f9c-41c1-aa63-9d850bcf2c04.png)
