### ISSUE TITLE
Change the unit at the depth sensor.

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#624]
https://forum.supla.org/viewtopic.php?p=130734#p130734

**Comment by fracz** [comment]
Dziwne, w całym kodzie nie ma ciągu znaków `m²`. Dopytałem autora o szczegóły.

**Comment by fracz** [comment]
> Już wiem gdzie jest problem przeglądarka podczas tłumaczenia na polski dopisuje m2 wyłączyłem tłumaczenie i jest ok.
> Widocznie smartfon też tłumaczył i też było źle.

¯\_(ツ)_/¯

**Comment by fracz** [comment]
> Już wiem gdzie jest problem przeglądarka podczas tłumaczenia na polski dopisuje m2 wyłączyłem tłumaczenie i jest ok.
> Widocznie smartfon też tłumaczył i też było źle.

¯\_(ツ)_/¯
