### ISSUE TITLE
Possibility to specify the added value for each of the phases separately. (As an additional option "Specify for each phase separately")

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#633]

**Comment by przemyslawzygmunt** [comment]
Simple mode (One value for all three phases):

{
   "electricityMeterInitialValues":{
      "forwardActiveEnergy":123.4567,
   }
}

Advanced mode (Separate value for each phase):
{
   "electricityMeterInitialValues":{
      "forwardActiveEnergy":{
         "1":12.34,
         "2":56.78,
         "3":910.12
      }
   }
}

Similarly for reverseActiveEnergy, forwardReactiveEnergy, reverseReactiveEnergy, forwardActiveEnergyBalanced, reverse Active Energy Balanced.

**Comment by fracz** [comment]
![image](https://user-images.githubusercontent.com/3918865/209665694-b3b39703-fd1c-4e18-895e-d09993e73d78.png)
![image](https://user-images.githubusercontent.com/3918865/209665776-271dd01b-265a-4f82-b6bf-fec646c96aa1.png)
![image](https://user-images.githubusercontent.com/3918865/209665832-a67b13bd-da6c-4ffb-b77d-51427e93d7ae.png)
