### ISSUE TITLE
Enabling logging into the account by the service technician

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#636]

**Comment by Basmart** [comment]
Hello Supla

**Comment by Basmart** [comment]
I was wondering for Service/Technitian account allowing setup and configuration on behalf of user (with user consent and approval)
Currently I have few Supla acocunts in the app but as it grows or phone is dead I woild like to be able to access my clients accounts as Service/Technitian remotley.

**Comment by fracz** [comment]
#460
