### ISSUE TITLE
cURL how to

### ISSUE THREAD

**Issue by Basmart** [SUPLA/supla-cloud#638]
when run this command from Windows CMD
**curl -s -H "Content-Type: application/json" -H "Accept: application/json" -X PATCH -d '{"code":"xxxxxxxxxxxxxxx","action":"read"}' https://svr31.supla.org/direct/1254**

I get this:
**{"status":400,"message":"Invalid json message received"}**

any suggestions?

**Comment by Basmart** [comment]
on  Debian works perfectly

**Comment by Basmart** [comment]
```
<?php

$url = "https://svrxxxxx.supla.org/direct/1254";

$curl = curl_init($url);
curl_setopt($curl, CURLOPT_URL, $url);
curl_setopt($curl, CURLOPT_PATCH, true);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);

$headers = array(
   "Content-Type: application/json",
   "Accept: application/json",
);
curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
curl_setopt($curl, CURLOPT_CUSTOMREQUEST, 'PATCH');

$data = '{"code":"XXXXXXXXXXXXXXXXXXXXXXXX","action":"execute"}';

curl_setopt($curl, CURLOPT_POSTFIELDS, $data);

//for debug only!
curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);

$resp = curl_exec($curl);
curl_close($curl);
var_dump($resp);

?>
```
Works as a charm.
I know... I am infant on this so every step makes me happy :-)

**Comment by Basmart** [comment]
Zostałem zaproszony przez Pana Przemka.

Już się przenoszę.



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Basmart** [comment]
Czy mam usunąć te posty?

Z github?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by klew** [comment]
Tutaj wystarczy, że zamkniesz issue

**Comment by Basmart** [comment]
Closed
