### ISSUE TITLE
Voltage aberrations - add the possibility of skipping selected phases

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#639]

**Comment by przemyslawzygmunt** [comment]
disabledPhases: [0, 1, 2]

**Comment by fracz** [comment]
![Image](https://user-images.githubusercontent.com/3918865/206860832-a2a3d47b-07e8-46ee-b177-5bb0018066df.png)

**Comment by przemyslawzygmunt** [comment]
Cloud should check which phases are available from the Flags variable at all. It should show "Enabled phases" buttons if the number of available phases > 1. It should not allow to exclude all phases.

Flags:
SUPLA_CHANNEL_FLAG_PHASE1_UNSUPPORTED 0x00020000 
SUPLA_CHANNEL_FLAG_PHASE2_UNSUPPORTED 0x00040000
SUPLA_CHANNEL_FLAG_PHASE3_UNSUPPORTED 0x00080000
