### ISSUE TITLE
Supla installation 

### ISSUE THREAD

**Issue by boualimed** [SUPLA/supla-cloud#65]
hi, 
please help,  I've tried to install Supla-cloud locally all things has done in the beginning, but when i try putting the credential email the login page went to this following error "This site can’t be reached

127.0.0.1 unexpectedly closed the connection."....;  how can i solve the problem.

**Comment by fracz** [comment]
Could you describe your problem in our forum, please? There are much more people who can help you.

https://forum.supla.org/viewforum.php?f=3

**Comment by boualimed** [comment]
ok
