### ISSUE TITLE
Add configuration parameters for Google Home. (Hide, PIN, Require Confirmation)

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#654]

**Comment by przemyslawzygmunt** [comment]
https://developers.home.google.com/cloud-to-cloud/enhancements/secondary-user-verification

**Comment by przemyslawzygmunt** [comment]
![Image](https://user-images.githubusercontent.com/6603397/203860418-9789e1a6-2201-4e57-86d4-d088c2c61267.png)

**Comment by fracz** [comment]
## Config for PIN

```
"googleHome": {
  "googleHomeDisabled": false,
  "needsUserConfirmation": false,
  "pin": "HASHED_PIN"
}
```

## Request without pin
`PATCH /api/channels/1`
`{"action":"turn-on","googleRequestId": "abcd"}`

Response:
```
{
    "status": 400,
    "message": "Param googlePin=PIN is required for this channel.",
    "details": {
        "needsPin": true
    }
}
```

## Request with invalid pin
`PATCH /api/channels/1`
`{"action":"turn-on","googleRequestId": "abcd", "googlePin": "1234"}`

Response:
```
{
    "status": 400,
    "message": "PIN sent in googlePin=PIN is invalid for this channel.",
    "details": {
        "invalidPin": true
    }
}
```

## Request with valid pin
`PATCH /api/channels/1`
`{"action":"turn-on","googleRequestId": "abcd", "googlePin": "1234"}`

Response (202, empty body):

**Comment by fracz** [comment]
## Config for user confirmation

```
"googleHome": {
  "googleHomeDisabled": false,
  "needsUserConfirmation": true,
  "pin": null
}
```

## Request without confirmation
`PATCH /api/channels/1`
`{"action":"turn-on","googleRequestId": "abcd"}`

Response:
```
{
    "status": 400,
    "message": "Param googleUserConfirmation=true is required for this channel.",
    "details": {
        "needsUserConfirmation": true
    }
}
```

## Request with user confirmation
`PATCH /api/channels/1`
`{"action":"turn-on","googleRequestId": "abcd", "googleUserConfirmation": true}`

Response (202, empty body)
