### ISSUE TITLE
Add showing older aberrations.

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#657]

**Comment by przemyslawzygmunt** [comment]
https://forum.supla.org/viewtopic.php?t=12029

**Comment by przemyslawzygmunt** [comment]
![Image](https://user-images.githubusercontent.com/6603397/206933285-f6954100-e305-4648-98ab-0bdbcdb3ee79.png)

**Comment by przemyslawzygmunt** [comment]
You can add some kind of filter where the user specifies the month they want to see but not beyond the data retention time limit.

**Comment by fracz** [comment]
Solved with inifinite scroll.
