### ISSUE TITLE
There are aberrations in the database, and the UI shows that there are none

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#659]

**Comment by przemyslawzygmunt** [comment]
![Image](https://user-images.githubusercontent.com/6603397/207639260-83d65dd6-da9f-441f-8b8c-842558a3b30b.png)



![Image](https://user-images.githubusercontent.com/6603397/207639371-28a90a7e-b92f-4d90-82dc-34a188258424.png)



[supla_em_voltage_log_kopia.sql.zip](https://github.com/SUPLA/supla-cloud/files/10229212/supla_em_voltage_log_kopia.sql.zip)

**Comment by fracz** [comment]
same as #657
