### ISSUE TITLE
The active energy chart is incorrectly generated.

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#668]

**Comment by przemyslawzygmunt** [comment]
![Image](https://user-images.githubusercontent.com/6603397/210825552-e5f8faa1-2695-4c4b-b6a0-9ce3e2c65a70.png)



[supla_em_log_kopia.sql.gz](https://github.com/SUPLA/supla-cloud/files/10353671/supla_em_log_kopia.sql.gz)

**Comment by fracz** [comment]
![image](https://user-images.githubusercontent.com/3918865/220634367-0e7c7e26-9a89-489c-9774-ea73db5a0e3a.png)

**Comment by fracz** [comment]
Problem jest gdy `phase1_fae` jest `NULL`

**Comment by przemyslawzygmunt** [comment]
Możesz się na to uodpornić ?

**Comment by fracz** [comment]
Jasne :-)
