### ISSUE TITLE
CSV generation - the ability to specify the chapter character at the decimal point separator

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#671]

**Comment by fracz** [comment]
Chodzi o to by dało się wybrać, czy separatorem dziesiętnym jest kropka czy przecinek? Przecież to bez sensu, przecinek będzie wymagał escapowania w CSV i będzie to wyglądać strasznie. Na pewno tego potrzebujemy?

**Comment by fracz** [comment]
Zamiast tego, dodałem opcję pobierania w różnych formatach (#671) i dodałem opcję ustalania separatora dla CSV.
