### ISSUE TITLE
Ability to download measurement history in xls format

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#672]

**Comment by fracz** [comment]
xlsx?

**Comment by przemyslawzygmunt** [comment]
Może ods ?

**Comment by przemyslawzygmunt** [comment]
To jest problem z rynku. Domyślnie otwierając ten plik w polskim Excelu wszystko jest w jednej kolumnie.
<img width="1197" alt="Zrzut ekranu 2023-02-22 o 14 29 39" src="https://user-images.githubusercontent.com/6603397/220633897-39464872-9d48-43cf-b66a-225d0e4bed69.png">

Można dodać w pierwszej linii sep=,

Wtedy otworzy się w miarę poprawnie, ale nadal wartości dziesiętne są niewłaściwie rozpoznawane i np. niektóre dane konwertowane są na daty:
<img width="1197" alt="Zrzut ekranu 2023-02-22 o 14 37 27" src="https://user-images.githubusercontent.com/6603397/220635752-2c09e407-09d5-4cf8-9924-6e50ac02e9ae.png">

**Comment by fracz** [comment]
![image](https://user-images.githubusercontent.com/3918865/226902014-f812a728-2bba-4ec7-8bda-0110a809b211.png)

**Comment by przemyslawzygmunt** [comment]
Ponadto dałbym możliwość wybrania okresu:
- cały okres
- zakres dat

**Comment by przemyslawzygmunt** [comment]
proc_nice(6)
