### ISSUE TITLE
Do we need supla_em_voltage_log.measurement_time_sec if the value is identical to supla_em_voltage_log.sec_total ?

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#679]

**Comment by fracz** [comment]
To raczej pytanie do Ciebie, Przemku? @przemyslawzygmunt 

Ja już pisałem że nie rozumiem dlaczego te wartości są takie same.

Implementując to myślałem, że sec_total to jest sumaryczny czas aberracji, a measurement_time_sec to liczba sekund (okno), w którym aberracje były monitorowane.

**Comment by przemyslawzygmunt** [comment]
W takim razie jedno możemy usunąć.

**Comment by fracz** [comment]
`sec_total` wyrzucone
