### ISSUE TITLE
Add support for the PN-GET-LIMIT command, which returns the limit of push notifications sent.

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#696]
https://github.com/SUPLA/supla-cloud/blob/8a47a54f54cd825b3ddd2f78338eeb9301a76617/src/SuplaBundle/Supla/SuplaServer.php#L325

Command: PN-GET-LIMIT:$userId
Example: PN-GET-LIMIT:123

Response: PN-LIMIT:$limit,$left

$limit - mark the limit of push messages that can be sent within an hour counting from the time of sending the first message. A value below zero means some error, or the user does not exist, or the user cannot send messages.
$left - specifies the number of messages that can still be sent. If the value is less than zero, it means the number of messages that have been rejected/omitted from the sending.

Do not read the limit directly from the database because the server reads it only after an hour from sending the first message, which means that when the user limit is changed, the server will still see the previous value for some time. Therefore, the cloud should get this data from the supla-server.

Example: PN-LIMIT:10,10
Example: PN-LIMIT:10,-10

**Comment by fracz** [comment]
![image](https://github.com/SUPLA/supla-cloud/assets/3918865/00b13ff9-f787-4ba4-a413-68135a976e9d)
