### ISSUE TITLE
Support for value-based action triggers. Called "Reactions".

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#702]

**Comment by fracz** [comment]
Propozycje ustawień wyzwalaczy:
Binary sensor (np. czujniki otwarcia) oraz OnOff (światło zasilanie)
{ eq: true/false }
Wyzwalacz zadziała na zmianę stanu równą true/false

Floating point sensor (np. czujnik odległości) oraz Rolety
{ ge: 123.456 }
Wyzwalacz zadziała jeśli nowa wartość będzie >= 123.456, a poprzednia < 123.456

{ ge: 123.456, reset_le: 100 }
Wyzwalacz zadziała jeśli nowa wartość będzie >= 123.456, a poprzednia < 123.456 i będzie nieczynny do czasu osiągnięcia wartości <= 100

RGBW

{ color: { eq: 0xAABBCC } }
Wyzwalacz zadziała jeśli nowy kolor będzie równy 0xAABBCC

{ color_brightness: { eq: 50 } }
Wyzwalacz zadziała jeśli nowa jasności koloru będzie równa 50%

{ color_brightness: { ge: 50, reset_le: 49 } }
Wyzwalacz zadziała jeśli nowa jasności koloru będzie >= 50, a poprzenia < 50 i będzie nieczynny do czasu osiągnięcia wartości <= 49

{ brightness: { eq: 50 } }
Wyzwalacz zadziała jeśli nowa jasności będzie równa 50%

{ brightness: { ge: 50, reset_le: 49 } }
Wyzwalacz zadziała jeśli nowa jasności będzie >= 50, a poprzednia < 50 i będzie nieczynny do czasu osiągnięcia wartości <= 49
Wszystkie kanały
{ online: true } - zadziała gdy kanał przejdzie ze stanu offline do online
{ online: false } - zadziała gdy kanał przejdzie ze stanu online do offline

**Comment by fracz** [comment]
🥳
