### ISSUE TITLE
Select dropdown list is drawn behind other elements

### ISSUE THREAD

**Issue by klew** [SUPLA/supla-cloud#725]
In some places, select dropdown list is drawn behind other elements - it should be on top.
![image](https://github.com/SUPLA/supla-cloud/assets/205610/aef9cba3-8ac8-4d62-8b4b-6f915f81bb74)

![image](https://github.com/SUPLA/supla-cloud/assets/205610/be208079-b29b-4572-9195-3a29c1b170d6)

**Comment by fracz** [comment]
Powyższe miejsca poprawione, ale jeszcze nie zamykam, poczekam na dalsze testy.

**Comment by fracz** [comment]
https://github.com/SUPLA/supla-cloud/commit/68e0a2d1612c283db86f27cc11086095652047d8
