### ISSUE TITLE
Errors when setting the reaction (production)

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#726]
<img width="1589" alt="Zrzut ekranu 2023-07-21 o 10 15 23" src="https://github.com/SUPLA/supla-cloud/assets/6603397/b4718d57-ed18-4725-883a-535f660acc67">

**Comment by fracz** [comment]
https://github.com/SUPLA/supla-cloud/commit/1a19d4069efe5fa9a7e922eb26de97a4efb54e49
