### ISSUE TITLE
Thermostat - wait for config from device, when channel config is missing

### ISSUE THREAD

**Issue by klew** [SUPLA/supla-cloud#728]
For new thermostat device, and after each change of thermostat channel function, whole thermostat configuration will be cleared (channel config, weekly schedule). In such case, Cloud should wait for device to reconnect after function change and for initial channel config to be filled.
When "channel config" is not available, Cloud should allow only:
 - change of thermostat function,
 - renaming channel,
 - changing channel visiblity.

**Comment by klew** [comment]
ICloud should clear channel config and weekly schedule config after function change.

**Comment by fracz** [comment]
Będzie zrobione w ramach https://github.com/SUPLA/supla-cloud/issues/739
