### ISSUE TITLE
History export to ODS contain invalid time

### ISSUE THREAD

**Issue by klew** [SUPLA/supla-cloud#729]
ODS export saves to file a time with +0 UTC instead of configured timezone.
Other export variants (xlsx, html, csv) have proper time.

I.e. xls export:
![image](https://github.com/SUPLA/supla-cloud/assets/205610/658351c3-81f4-434f-9a53-bf543eef8fc3)

ODS export:
![image](https://github.com/SUPLA/supla-cloud/assets/205610/7d535f7e-3c36-4d73-9770-fd6ef479fbcf)

**Comment by fracz** [comment]
Nie wiem dlaczego, ale opcja `cellDates` powodowała ten problem.

https://docs.sheetjs.com/docs/csf/features/dates/#how-sheetjs-handles-dates-and-times

Usunięte.

**Comment by fracz** [comment]
https://github.com/SUPLA/supla-cloud/commit/42b66e96ca8a44d6db4ff5fc32f9fc1910e4fcc0
