### ISSUE TITLE
Termostat

### ISSUE THREAD

**Issue by fracz** [SUPLA/supla-cloud#733]
chciałbym jeszcze poruszyć temat termostatu w Cloud - czy mamy tutaj jakiś plan, kiedy prace w tym zakresie ruszą?
Ja widzę tutaj takie zagadnienia:
- [ ] Plan minimum raczej nie będzie bardzo skomplikowany - potrzebujemy przede wszystkim pozwalać na konfigurację termostatu (czyli zmiana funkcji oraz ustawienie tych kilkunastu parametrów konfiguracyjnych)
- [ ] W kolejnym kroku możemy pomyśleć o ustawianiu harmonogramu tygodniowego z Clouda (coś podobnego do harmonogramu aktywności, tylko mamy podział na kwadranse i do ustawienia 4 różne programy oraz off)
- [ ] W kolejnym kroku możemy ustalić jakie akcje ma wspierać termostat i udostępnić je w Wyzwalaczach, Reakcjach, Harmonogramach, API, itd
- [ ] I na koniec można pomyślęć o prezentowaniu stanu termostatu w Cloud-
- [ ] Termostat może też generować reakcje

Myślę, że najszybciej potrzeba 1. Natomiast pozostałe mogą być później

**Comment by klew** [comment]
Issue dotyczące pierwszego punktu "plan minimum": #738, #728, #739, #740

**Comment by przemyslawzygmunt** [comment]
Przy projektowaniu API należy uwzględnić potencjalną integrację z GH/Alexa/HA

**Comment by przemyslawzygmunt** [comment]
Ustawienia kanału zapisywane są w supla_dev_channel.user_config w formacie json.
Ustawienia urządzenia zapisywane są w supla_iodevice.user_config również w formacie json.
Procedura zapisu powinna uwzględniać możliwość równoległego dostępu do danych. 

https://github.com/SUPLA/supla-core/blob/0799504a04dff8b0dcde03dc34abd813c937903d/supla-server/src/device/device_dao.cpp#L1133
https://github.com/SUPLA/supla-cloud/blob/b33158cac926f775d844dc39bfdd7a940699c0a7/app/DoctrineMigrations/Version20230604004315.php#L29

![UserConfig drawio (4)](https://github.com/SUPLA/supla-cloud/assets/6603397/b13600db-04a6-4c45-ac3d-bf275168068e)

**Comment by przemyslawzygmunt** [comment]
supla_iodevice.user_config - poniżej możliwe klucze. Jeśli danego klucza nie ma to nie wyświetlamy go w UI.

{"statusLed":"AlwaysOff","screenBrightness":24,"buttonVolume":100,"userInterfaceDisabled":false,"automaticTimeSync":true,"screenSaver":{"delay":123,"mode":"TimeDate","modesAvailable":["Off","Temperature","Humidity","Time","TimeDate","TemperatureTime","MainAndAuxTemperature"]}}

Możliwe wartości dla "statusLed": "OffWhenConnected", "AlwaysOff", "OnWhenConnected".
Możliwe wartości dla screenSaver->mode: "Off", "Temperature", "Humidity", "Time", "TimeDate", "TemperatureTime", "MainAndAuxTemperature".  Tablica screenSaver->modesAvailable określa jakie tryby są dostępne.
"screenBrightness" może przyjmować wartości od 0 do 100 lub "auto".

**Comment by przemyslawzygmunt** [comment]
supla_dev_channel.user_config - cała konfiguracja dla kanału typu
HVAC https://github.com/SUPLA/supla-core/blob/proto_v21/supla-common/proto.h#L411
mieści się w {"hvac": {}}.

Przykładowa konfiguracja:
{"hvac":{"mainThermometerChannelNo":0,"auxThermometerChannelNo":1,"auxThermometerType":"Floor","antiFreezeAndOverheatProtectionEnabled":false,"availableAlgorithms":["OnOffSetpointMiddle"],"usedAlgorithm":"OnOffSetpointMiddle","minOnTimeS":0,"minOffTimeS":0,"outputValueOnError":0,"temperatures":{"6":40,"11":1000,"12":4000,"13":500,"14":7500,"15":20,"16":1000,"17":200,"18":1000},"weeklySchedule":{"programSettings":{"1":{"mode":"Cool","setpointTemperatureMin":0,"setpointTemperatureMax":2400},"2":{"mode":"Cool","setpointTemperatureMin":0,"setpointTemperatureMax":2100},"3":{"mode":"Cool","setpointTemperatureMin":0,"setpointTemperatureMax":1800},"4":{"mode":"Cool","setpointTemperatureMin":0,"setpointTemperatureMax":2800}},"quarters":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,2,2,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,2,2,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,2,2,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,2,2,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,2,2,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0]}}}

https://github.com/SUPLA/supla-core/blob/0799504a04dff8b0dcde03dc34abd813c937903d/supla-common/proto.h#L2561

mainThermometerChannelNo - Numer kanału głównego termometru. Zawsze to samo urządzenie. Nie mylić z Id.
auxThermometerChannelNo - Numer kanału dodatkowego
auxThermometerType - Rodzaj kanału dodatkowego. Możliwe wartości: "NotSet", "Disabled", "Floor", "Wather", "GenericHeater", "GenericCooler".
antiFreezeAndOverheatProtectionEnabled - true/false.
availableAlgorithms - dostępne algorytmy. Obecnie możliwe są dwa "OnOffSetpointMiddle", "OnOffSetpointAtMost".
usedAlgorithm - wybrany algorytm.
minOnTimeS -  od 0 do 600 sekund
minOffTimeS -  od 0 do 600 sekund
outputValueOnError - od  -100 do 100
temperatures - ustawienia poszczególnych temperatur https://github.com/SUPLA/supla-core/blob/0799504a04dff8b0dcde03dc34abd813c937903d/supla-common/proto.h#L1987 TEMPERATURE_FREEZE_PROTECTION to index 1, TEMPERATURE_ECO to 2 itd.

Mnożnik dla temperatur = 0.01

{"hvac": {"weeklySchedule":{}}} określa ustawienia dla kalendarza tygodniowego.

programSettings zawiera ustawienia trybów i temperatur dla poszczególnych programów. Programy są numerowane od 1 do 4 przy czym 0 to "off".

setpointTemperatureMax jest ustawiane jeśli wybrano tryb "Cool". setpointTemperatureMin jeśli wybrano tryb "Heat". 
setpointTemperatureMin i setpointTemperatureMax są ustawiane dla trybu "auto".

"quarters" zawiera informacje jaki jest program dla kolejnego kwadrans-u licząc od 00:00.
Czyli pierwsza wartość to to 00:00 , druga to 00:15, trzecia 00:30 itd.
