### ISSUE TITLE
Thermostat - channel function change

### ISSUE THREAD

**Issue by klew** [SUPLA/supla-cloud#738]
HVAC/Thermostat channel type: 6100

Add support for following functions: 
SUPLA_CHANNELFNC_HVAC_THERMOSTAT 420
SUPLA_CHANNELFNC_HVAC_DOMESTIC_HOT_WATER 426

In near future also SUPLA_CHANNELFNC_HVAC_THERMOSTAT_AUTO 422 will be added.

Functions supported by channel are specified in channel's FuncList as a bitmap:
#define SUPLA_HVAC_CAP_FLAG_MODE_ONOFF 0x0001
#define SUPLA_HVAC_CAP_FLAG_MODE_AUTO 0x0002   // <- if set, AUTO function is supported
#define SUPLA_HVAC_CAP_FLAG_MODE_COOL 0x0004   // <- if set, HVAC_THERMOSTAT function is supported
#define SUPLA_HVAC_CAP_FLAG_MODE_HEAT 0x0008   // <- if set, HVAC_THERMOSTAT function is supported
#define SUPLA_HVAC_CAP_FLAG_MODE_DRY 0x0010
#define SUPLA_HVAC_CAP_FLAG_MODE_FAN 0x0020
#define SUPLA_HVAC_CAP_FLAG_DIFFERENTIAL 0x0040
#define SUPLA_HVAC_CAP_FLAG_DOMESTIC_HOT_WATER 0x0080     // <- if set, DOMESTIC HOT WATER function is supported

Other cap_flags may be ignored currently.

#728 is also needed here.

**Comment by fracz** [comment]
https://github.com/SUPLA/supla-core/blob/9bc122ef8ffee24787846e5bd91c70da28bbef3d/supla-common/proto.h#L502
