### ISSUE TITLE
Thermostat - channel configuration

### ISSUE THREAD

**Issue by klew** [SUPLA/supla-cloud#739]
After device registration or after function change, Cloud will wait for device to fill default config on server.
Once it is available, Cloud should allow to configure thermostat.

Thermostat configuration:
1. Ability to select main thermometer from thermometers (and huimdity+temperature) available on the same device. Main thermometer is mandatory.
2. Ability to select aux thermometer. It has to be from the same device and has to be different than "main thermometer". When aux thermometer is selected, then additional "subfunction" should be provided: 
#define SUPLA_HVAC_AUX_THERMOMETER_TYPE_NOT_SET 0
#define SUPLA_HVAC_AUX_THERMOMETER_TYPE_DISABLED 1
#define SUPLA_HVAC_AUX_THERMOMETER_TYPE_FLOOR 2
#define SUPLA_HVAC_AUX_THERMOMETER_TYPE_WATER 3
#define SUPLA_HVAC_AUX_THERMOMETER_TYPE_GENERIC_HEATER 4
#define SUPLA_HVAC_AUX_THERMOMETER_TYPE_GENERIC_COOLER 5
3. Option to select thermostat algorithm. Capabilities are stored in bitmap AvailableAlgorithms and selected value is in UsedAlgorithm. Currently we have two options: "ON/OFF with histeresis around temperature setpoint" and "ON/OFF with histeresis set below or above temperature setpoint" (probably some tooltip or simple graphic with explanation should be added)
4. MinOnTimeS and MinOffTimeS - minimum allowed time for output to be enabled od disabled (i.e. MinOnTimeS 60 s means that theremostat will aloways enable output for at least 60 s even if after 20 s temperature will be above configured setpoint). Allowed range 0-600 s.
5. OutputValueOnError: 0 off (default), 100 heat, -100 cool. Heat or cool should be available if such functionality is supported. Currently fixed values. In future it may be redefined to be in range -100 .. 100. Add warning that changing this value may be dangerours
6. AntiFreezeAndOverheatProtectionEnabled - enabling of antifreeze and overhea protection (actual function depends on thermostat function, i.e. for HEAT function only antifreeze is supported.

Additionally there are temperatures in configuration. Some of them are readonly for Cloud:
// Minimum room (main thermometer) temperature to be set by user 
#define TEMPERATURE_ROOM_MIN (1ULL << 10)
// Maximum room (main thermometer) temperature to be set by user
#define TEMPERATURE_ROOM_MAX (1ULL << 11)
// Minimum allowed temperature for heat/cold source (used with second
// thermomter for floor/water/etc.)
#define TEMPERATURE_AUX_MIN (1ULL << 12)
// Maximum allowed temperature for heat/cold source
#define TEMPERATURE_AUX_MAX (1ULL << 13)
// Minimum histereis value
#define TEMPERATURE_HISTERESIS_MIN (1ULL << 14)
// Maximum histereis value
#define TEMPERATURE_HISTERESIS_MAX (1ULL << 15)
// Minimum temperature offset in AUTO mode
#define TEMPERATURE_AUTO_OFFSET_MIN (1ULL << 16)
// Maximum temperature offset in AUTO mode
#define TEMPERATURE_AUTO_OFFSET_MAX (1ULL << 17)

Above temperatures defines constrains for other temperature setting.
Temperature validation rules:
 - Temperature in "Room Constrain" means:
     TEMPERATURE_ROOM_MIN <= t <= TEMPERATURE_ROOM_MAX
 - Temperature in "Aux Constrain" means:
     TEMPERATURE_AUX_MIN <= t <= TEMPERATURE_AUX_MAX
 - Temperatures (t_min, t_max) in "Auto Constrain" means:
     TEMPERATURE_ROOM_MIN <= t_min <= TEMPERATURE_ROOM_MAX AND
     TEMPERATURE_ROOM_MIN <= t_max <= TEMPERATURE_ROOM_MAX AND
     (t_max - t_min >= TEMPERATURE_AUTO_OFFSET_MIN) AND
     (t_max - t_min <= TEMPERATURE_AUTO_OFFSET_MAX)

User configurable temperatures:
TEMPERATURE_FREEZE_PROTECTION - has to be in Room Constrain when AntiFreezeAndOverheatProtectionEnabled is set
TEMPERATURE_ECO - has to be in Room Constrain (don't add it now - may be used later)
TEMPERATURE_COMFORT - has to be in Room Constrain (don't add it now - may be used later)
TEMPERATURE_BOOST - has to be in Room Constrain (don't add it now - may be used later)
TEMPERATURE_HEAT_PROTECTION - has to be in Room Constrain when function is COOL or AUTO and AntiFreezeAndOverheatProtecionEnabled is set
TEMPERATURE_HISTERESIS - has to be TEMPERATURE_HISTERESIS_MIN <= t <= TEMPERATURE_HISTERESIS_MAX
TEMPERATURE_BELOW_ALARM - has to be in Room Constrain  (don't add it now - may be used later)
TEMPERATURE_ABOVE_ALARM - has to be in Room Constrain (don't add it now - may be used later)
TEMPERATURE_AUX_MIN_SETPOINT - has to be in Aux Constrain and has to be < TEMPERATURE_AUX_MAX_SETPOINT
TEMPERATURE_AUX_MAX_SETPOINT - has to be in Aux Constrain and has to be > TEMPERATURE_AUX_MIN_SETPOINT

Aux min/max setpoint is minimum and/or maximum temperature value to be kept (according to aux thermomemer) i.e. it may keep floor temperature between 21 and 27 degrees, regardless of room temperature.

Temperatures may be set to some value, or not set (i.e. "null"). From above list TEMPERATURE_HISTERESIS is mandatory and has to be set.
Also freeze and overheat protection has to be set when protection is enabled and proper function is set.
"aux min/max setpoint" should be possible to clear - when it is missing, then functionality is disabled.

Above description is about "HVAC channel" configuration. There is also additional (and new) device configuration which is described in another issue.

**Comment by fracz** [comment]
supla_dev_channel.user_config - cała konfiguracja dla kanału typu
Myślę, że możemy też przyjąć, że UI cloud-a wyświetli formularz dopiero gdy w bazie będzie uzupełniony podstawowy config czyli urządzenie się poprawnie zarejestruje i prześle poprawną konfigurację.
HVAC https://github.com/SUPLA/supla-core/blob/proto_v21/supla-common/proto.h#L411
mieści się w {"hvac": {}}.

Przykładowa konfiguracja:
{"hvac":{"mainThermometerChannelNo":0,"auxThermometerChannelNo":1,"auxThermometerType":"Floor","antiFreezeAndOverheatProtectionEnabled":false,"availableAlgorithms":["OnOffSetpointMiddle"],"usedAlgorithm":"OnOffSetpointMiddle","minOnTimeS":0,"minOffTimeS":0,"outputValueOnError":0,"temperatures":{"6":40,"11":1000,"12":4000,"13":500,"14":7500,"15":20,"16":1000,"17":200,"18":1000},"weeklySchedule":{"programSettings":{"1":{"mode":"Cool","setpointTemperatureMin":0,"setpointTemperatureMax":2400},"2":{"mode":"Cool","setpointTemperatureMin":0,"setpointTemperatureMax":2100},"3":{"mode":"Cool","setpointTemperatureMin":0,"setpointTemperatureMax":1800},"4":{"mode":"Cool","setpointTemperatureMin":0,"setpointTemperatureMax":2800}},"quarters":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,2,2,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,2,2,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,2,2,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,2,2,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,2,2,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0]}}}

https://github.com/SUPLA/supla-core/blob/0799504a04dff8b0dcde03dc34abd813c937903d/supla-common/proto.h#L2561

mainThermometerChannelNo - Numer kanału głównego termometru. Zawsze to samo urządzenie. Nie mylić z Id.
auxThermometerChannelNo - Numer kanału dodatkowego
auxThermometerType - Rodzaj kanału dodatkowego. Możliwe wartości: "NotSet", "Disabled", "Floor", "Wather", "GenericHeater", "GenericCooler".
antiFreezeAndOverheatProtectionEnabled - true/false.
availableAlgorithms - dostępne algorytmy. Obecnie możliwe są dwa "OnOffSetpointMiddle", "OnOffSetpointAtMost".
usedAlgorithm - wybrany algorytm.
minOnTimeS - od 0 do 600 sekund
minOffTimeS - od 0 do 600 sekund
outputValueOnError - od -100 do 100
temperatures - ustawienia poszczególnych temperatur https://github.com/SUPLA/supla-core/blob/0799504a04dff8b0dcde03dc34abd813c937903d/supla-common/proto.h#L1987 TEMPERATURE_FREEZE_PROTECTION to index 1, TEMPERATURE_ECO to 2 itd.

Mnożnik dla temperatur = 0.01

{"hvac": {"weeklySchedule":{}}} określa ustawienia dla kalendarza tygodniowego.

programSettings zawiera ustawienia trybów i temperatur dla poszczególnych programów. Programy są numerowane od 1 do 4 przy czym 0 to "off".

setpointTemperatureMax jest ustawiane jeśli wybrano tryb "Cool". setpointTemperatureMin jeśli wybrano tryb "Heat".
setpointTemperatureMin i setpointTemperatureMax są ustawiane dla trybu "auto".

"quarters" zawiera informacje jaki jest program dla kolejnego kwadrans-u licząc od 00:00.
Czyli pierwsza wartość to to 00:00 , druga to 00:15, trzecia 00:30 itd.

**Comment by fracz** [comment]
W ramach zadania też trzeba poczekać na konfigurację od urządzenia: https://github.com/SUPLA/supla-cloud/issues/728

For new thermostat device, and after each change of thermostat channel function, whole thermostat configuration will be cleared (channel config, weekly schedule). In such case, Cloud should wait for device to reconnect after function change and for initial channel config to be filled.
When "channel config" is not available, Cloud should allow only:

change of thermostat function,
renaming channel,
changing channel visiblity.

**Comment by klew** [comment]
Niedawno te "setpointTemperatureMax" oraz "setpointTemperatureMin" zmieniły nazwy na "setpointTemperatureCool" oraz "setpointTemperatureHeat".

Dla funkcji SUPLA_CHANNELFNC_HVAC_THERMOSTAT są dostępne dwa weeklySchedule (podstawowy dla subfunction==HEAT oraz alternatywny "alt" dla subfunction==COOL)

Do configa doszło też pole "Subfunction" (0 N/A, 1 Heat, 2 Cool) dla funkcji SUPLA_CHANNELFNC_HVAC_THERMOSTAT. Pozawala ono na przełącznie między grzaniem a chłodzeniem dla termostatów jednym wyjściem.

Doszedł też tam parametr "TemperatureSetpointChangeSwitchesToManualMode" (0 off, 1 on) - ale nie wiem jak to w bazie wygląda.

**Comment by fracz** [comment]
Example config:


```json
{
    "hvac": {
        "mainThermometerChannelNo": 0,
        "auxThermometerChannelNo": 1,
        "auxThermometerType": "Floor",
        "antiFreezeAndOverheatProtectionEnabled": false,
        "availableAlgorithms": [
            "OnOffSetpointMiddle"
        ],
        "usedAlgorithm": "OnOffSetpointMiddle",
        "minOnTimeS": 0,
        "minOffTimeS": 0,
        "outputValueOnError": 0,
        "temperatures": {
            "6": 40,
            "11": 1000,
            "12": 4000,
            "13": 500,
            "14": 7500,
            "15": 20,
            "16": 1000,
            "17": 200,
            "18": 1000
        },
        "weeklySchedule": {
            "programSettings": {
                "1": {
                    "mode": "Cool",
                    "setpointTemperatureMin": 0,
                    "setpointTemperatureMax": 2400
                },
                "2": {
                    "mode": "Cool",
                    "setpointTemperatureMin": 0,
                    "setpointTemperatureMax": 2100
                },
                "3": {
                    "mode": "Cool",
                    "setpointTemperatureMin": 0,
                    "setpointTemperatureMax": 1800
                },
                "4": {
                    "mode": "Cool",
                    "setpointTemperatureMin": 0,
                    "setpointTemperatureMax": 2800
                }
            },
            "quarters": [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                2,
                2,
                2,
                2,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                2,
                2,
                2,
                2,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                2,
                2,
                2,
                2,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                2,
                2,
                2,
                2,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                2,
                2,
                2,
                2,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
            ]
        }
    }
}
```
