### ISSUE TITLE
Device configuration

### ISSUE THREAD

**Issue by klew** [SUPLA/supla-cloud#740]
With thermostats we introduce device configuration capability for majority of parameters which were available only in device's config mode (including new parameters applicable to thermostat only).

Device reports to server, which config fields are supported.
Current list of fields:
https://github.com/SUPLA/supla-core/blob/0799504a04dff8b0dcde03dc34abd813c937903d/supla-common/proto.h#L548

For each field, there is corresponding structure (as mentioned in comment in above link) with allowed values, etc.

**Comment by fracz** [comment]
supla_iodevice.user_config - poniżej możliwe klucze. Jeśli danego klucza nie ma to nie wyświetlamy go w UI.

{"statusLed":"AlwaysOff","screenBrightness":24,"buttonVolume":100,"userInterfaceDisabled":false,"automaticTimeSync":true,"screenSaver":{"delay":123,"mode":"TimeDate","modesAvailable":["Off","Temperature","Humidity","Time","TimeDate","TemperatureTime","MainAndAuxTemperature"]}}

Możliwe wartości dla "statusLed": "OffWhenConnected", "AlwaysOff", "OnWhenConnected".
"screenBrightness" od 0 do 100.
"buttonVolume" od 0 do 100.
"userInterfaceDisabled" true/false.
"automaticTimeSync" true/false.
screenSaver->delay czas liczony w milisekundach. 0 - disabled (max int16)

Możliwe wartości dla screenSaver->mode: "Off", "Temperature", "Humidity", "Time", "TimeDate", "TemperatureTime", "MainAndAuxTemperature". Tablica screenSaver->modesAvailable określa jakie tryby są dostępne.
"screenBrightness" może przyjmować wartości od 0 do 100 lub "auto".

**Comment by przemyslawzygmunt** [comment]
To się minimalnie zmieniło w obszarze screenSaver.
Poniżej jeszcze raz wszystkie zmienne dla user_config.

{"statusLed": "OFF_WHEN_CONNECTED"} - możliwe wartości: "OFF_WHEN_CONNECTED", "ALWAYS_OFF", "ON_WHEN_CONNECTED".
{"screenBrightness": 100} - możliwy zakres to 0-100 lub "auto".
{"buttonVolume": 100} - możliwy zakres to 0-100.
{"userInterfaceDisabled": false} - możliwe true/false.
{"automaticTimeSync": true} - możliwe true/false.
{"screenSaver": {mode: "OFF"}} - możliwe tryby "OFF", "TEMPERATURE", "HUMIDITY", "TIME", "TIME_DATE", "TEMPERATURE_TIME", "MAIN_AND_AUX_TEMPERATURE".
{"screenSaver": {mode: "OFF", delay: 1000}} - czas w miliksekundach 
z natury rzeczy screenSaver może wyglądać tak: {"screenSaver": {mode: "TEMPERATURE", delay: 5000}}

Zmienne dla "properties":

{"screenSaverModesAvailable": ["OFF", "TEMPERATURE", "HUMIDITY", "TIME", "TIME_DATE", "TEMPERATURE_TIME", "MAIN_AND_AUX_TEMPERATURE"]} - w tablicy ująłem wszystko co jest obecnie możliwe.

**Comment by fracz** [comment]
Screen saver:

```json
{
  "homeScreen": {
    "mode": "TEMPERATURE",
    "delay": 5,
  }
}
```
