### ISSUE TITLE
Channels related to each other must be in the same location. Prevent changing the location if the new location is different from the location of the associated channel. In addition, which is very important, the sub-channel cannot be hidden.

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#745]

**Comment by przemyslawzygmunt** [comment]
When migrating the database, it is worth checking whether the related channels have a compatible location.

**Comment by fracz** [comment]
Czy to dotyczy tylko termostatów, czy wszystkich kanałów zależnych (czujniki bram itp)?

**Comment by klew** [comment]
Problem jest wspólny dla wszystkich połączeń. Obecnie mamy zgłoszone issue na dziwne zachowania, gdy mamy przekaźnik+licznik energii i gdy się ja ukrywa/przenosi do innych lokalizacji.
Tam jeszcze jest problem związany z tym, że jeden kanał może być online a drugi offline, ale tego już nie da się wymusić od strony konfiguracji :).
Także ja byłbym za zaaplikowaniem tych reguł wszędzie, tylko że aktualny stan bazy może być sprzeczny z tymi regułami
