### ISSUE TITLE
Thermostat actions from Cloud

### ISSUE THREAD

**Issue by fracz** [SUPLA/supla-cloud#749]
Wg mnie takie akcje z poziomu clouda się przydadzą (przyciski, harmonogramy, sceny, wyzwalacze itp):
- włącz
- wyłącz
- włącz tryb ręczny (z podaniem mode oraz temperatury - opcjonalnie)
- włącz tryb programu tygodniowego (weekly schedule)
- ustaw temperaturę(y) (przy termostatach AUTO jest osobno temperatura grzewcza i chłodnicza)
- włącz tryb czasowy (off, lub ręczny - z dodatkowymi mode i temperaturami, lub bez)

tryb ręczny może mieć mode heat, cool, auto (zależnie od tego co termostat wspiera i od aktualnej subfunction).
W trybie heat ustawiamy temperaturę grzewczą, w trybie cool temperaturę chłodniczą.

przełącz/toggle?

toggle też może być, ale realizowane przez serwer/clouda, bo urządzenie nie ma takiej komendy

@klew @przemyslawzygmunt

**Comment by klew** [comment]
ACTION_SET_HVAC_PARAMETERS:%userId,%deviceid,%channelid,%duration,%mode,%setpointheat,%setpointcool,%flags

%mode: possible values:
https://github.com/SUPLA/supla-core/blob/49de83999f7d86039066b4f8a34105326d708eca/supla-common/proto.h#L784
```
#define SUPLA_HVAC_MODE_NOT_SET 0
#define SUPLA_HVAC_MODE_OFF 1
#define SUPLA_HVAC_MODE_HEAT 2
#define SUPLA_HVAC_MODE_COOL 3
#define SUPLA_HVAC_MODE_AUTO 4
#define SUPLA_HVAC_MODE_FAN_ONLY 6
#define SUPLA_HVAC_MODE_DRY 7
#define SUPLA_HVAC_MODE_CMD_TURN_ON 8
#define SUPLA_HVAC_MODE_CMD_WEEKLY_SCHEDULE 9
#define SUPLA_HVAC_MODE_CMD_SWITCH_TO_MANUAL 10
```

%setpoinheat: heat temperature setpoint value. Stored as int16 type, where 1 = 0.01 Celcius degree. Value is present only if proper flag is set. When flag is missing, use 0 value here.
%setpointcool: cool temperature setpoint value. Units as for setpointheat.
%flags: bitfield. From action pov only two flags are important: 
https://github.com/SUPLA/supla-core/blob/49de83999f7d86039066b4f8a34105326d708eca/supla-common/proto.h#L758C1-L759C65
```
#define SUPLA_HVAC_VALUE_FLAG_SETPOINT_TEMP_HEAT_SET (1ULL << 0)
#define SUPLA_HVAC_VALUE_FLAG_SETPOINT_TEMP_COOL_SET (1ULL << 1)
```
Bit should be set when setpointheat and/or cool values are set in command.

%duration - duration time of command/mode in seconds. Use 0 if not set.

### Turn on
ACTION_SET_HVAC_PARAMETERS:%userId,%deviceid,%channelid,0,8,0,0,0

### Turn off
ACTION_SET_HVAC_PARAMETERS:%userId,%deviceid,%channelid,0,1,0,0,0

### Switch to manual mode
**Just switch to manual mode** without providing any extra parameters. It will restore last used manual mode and setpoints:
ACTION_SET_HVAC_PARAMETERS:%userId,%deviceid,%channelid,0,10,0,0,0

**Switch to manual mode heat** (only for HVAC_THERMOSTAT with subfunction=HEAT, for HVAC_DOMESTIC_HOT_WATER, HVAC_DIFFERENTIAL, HVAC_THERMOSTAT_AUTO), no new temperature setpoints (thermostat will restore last used setpoints):
ACTION_SET_HVAC_PARAMETERS:%userId,%deviceid,%channelid,0,2,0,0,0

**Switch to manual mode cool** (only for HVAC_THERMOSTAT with subfunction=COOL, and for HVAC_THERMOSTAT_AUTO), no new temperature setpoints (thermostat will restore last used setpoints):
ACTION_SET_HVAC_PARAMETERS:%userId,%deviceid,%channelid,0,3,0,0,0

**Switch to manual mode auto** (only for HVAC_THERMOSTAT_AUTO), no new temperature setpoints (thermostat will restore last used setpoints):
ACTION_SET_HVAC_PARAMETERS:%userId,%deviceid,%channelid,0,4,0,0,0

Switch to manual mode with heat temperature setpoint set:
ACTION_SET_HVAC_PARAMETERS:%userId,%deviceid,%channelid,0,X,2300,0,1

Switch to manual mode with cool temperature setpoint set:
ACTION_SET_HVAC_PARAMETERS:%userId,%deviceid,%channelid,0,X,0,2500,2

Switch to manual mode with heat and cool temperature setpoints set:
ACTION_SET_HVAC_PARAMETERS:%userId,%deviceid,%channelid,0,X,2100,2500,3

`3 = 1 | 2`

 X in 3 above commands is one of 2, 3, 10. Setpoint heat is only supported in thermostats which supports mode heat. Setpoint cool is only supported in thermostats which supports cool mode.
 
### Switch to weekly schedule (program) mode
ACTION_SET_HVAC_PARAMETERS:%userId,%deviceid,%channelid,0,9,0,0,0

### Set temperature only
ACTION_SET_HVAC_PARAMETERS:%userId,%deviceid,%channelid,0,0,2100,0,1 - heating
ACTION_SET_HVAC_PARAMETERS:%userId,%deviceid,%channelid,0,0,0,1500,2 - cooling
ACTION_SET_HVAC_PARAMETERS:%userId,%deviceid,%channelid,0,0,2100,1500,3 - heating and cooling

In above examples, mode is "not set" (0). Actual behavior of thermostat will depend on current setting. If it is off -> it will turn on and set manual mode temperatures to values given above.
If it is in manual mode, it will set new temperature setpoints as in command.
If it is in weekly schedule mode, it will either:
 - switch to manual mode permamently and apply temperatures
 - temperarly swtich to manual mode and apply temperatures
 Actual behavior will depend on thermostat configuration settings.
 
 ### Countdown timer commands
For countdown timer user can request only "turn off" and "manual" function (with optional temperature setpoints). Duration is int32 in seconds. From Supla app we will provide countdown settings for days/hours/minutes and additionaly there will be option to select end date/time from calendar.
All above rules for setting mode and setpoints apply here, so below line are just two examples:
ACTION_SET_HVAC_PARAMETERS:%userId,%deviceid,%channelid,3600,1,0,0,0  - turn on for 3600 s = 1 h
ACTION_SET_HVAC_PARAMETERS:%userId,%deviceid,%channelid,7200,2,2300,0,1 - switch to manual mode heat with 23.0 setpoint for 2 h.

**Comment by fracz** [comment]
`ACTION_SET_HVAC_PARAMETERS:%userId,%deviceid,%channelid,%duration,%mode,%setpointheat,%setpointcool,%flags`

**Comment by fracz** [comment]
Wszystkie operacje wł/wył teraz są przesyłane do IPC jako `ACTION-TURN-ON` albo `ACTION-TURN-OFF`.

Przykładowo, żądanie z alexy do tej pory było:

`SET-CHAR-VALUE:1,1,2,3,ALEXA-CORRELATION-TOKEN=dW5pY29ybg==`

teraz będzie:

`ACTION-TURN-ON:1,2,3,ALEXA-CORRELATION-TOKEN=dW5pY29ybg==`

**Comment by fracz** [comment]
## Akcje do wyknania na funkcjach HVAC

```
const HVAC_SET_WEEKLY_SCHEDULE = 231;
const TURN_OFF_TIMER = 232;
const HVAC_SWITCH_TO_MANUAL = 233;
const HVAC_SET_TEMPERATURES = 234;
```

## Parametry akcji w bazie danych

### `231`

Brak

### `232`

```json
{"duration":900}
```

### `233`

```json
{"setpoints":{"heat":2100, "cool": 2300},"duration":1080,"mode":"AUTO"}
```
Wszystkie klucze są opcjonalne i może ich nie być.
mode ma wartość: `AUTO`, `COOL` albo `HEAT`.

### `234`

```json
{"setpoints":{"heat":2100, "cool": 2300}}
```
Może nie być jednego z kluczy `heat` albo `cool`.
