### ISSUE TITLE
Notify supla server about device config changes

### ISSUE THREAD

**Issue by fracz** [SUPLA/supla-cloud#756]
`DEVICE-CONFIG-CHANGED:%userId,%deviceId` - na zmianę configu IO (nowość)
stare `DEVICE-SETTINGS-CHANGED` jest zastępowane przez `CHANNEL-CONFIG-CHANGED` z listą zmian w base64

**Comment by przemyslawzygmunt** [comment]
#define CONFIG_CHANGE_SCOPE_OTHER 0x1
#define CONFIG_CHANGE_SCOPE_FUNCTION 0x2
#define CONFIG_CHANGE_SCOPE_HVAC 0x4
#define CONFIG_CHANGE_SCOPE_WEEKLY_SCHEDULE 0x8
#define CONFIG_CHANGE_SCOPE_ALT_WEEKLY_SCHEDULE 0x10

USER-ON-CHANNEL-CONFIG-CHANGED:%userId,%deviceId,%channelId,%type,%func,%scope
USER-ON-DEVICE-CONFIG-CHANGED:%userId,%deviceId

**Comment by fracz** [comment]
#define CONFIG_CHANGE_SCOPE_FUNCTION 0x1
#define CONFIG_CHANGE_SCOPE_CAPTION 0x2
#define CONFIG_CHANGE_SCOPE_LOCATION 0x4
#define CONFIG_CHANGE_SCOPE_VISIBILITY 0x8
#define CONFIG_CHANGE_SCOPE_ICON 0x10
#define CONFIG_CHANGE_SCOPE_JSON_BASIC 0x20 (lub CONFIG_CHANGE_SCOPE_JSON_GENERAL)
#define CONFIG_CHANGE_SCOPE_JSON_WEEKLY_SCHEDULE 0x40
#define CONFIG_CHANGE_SCOPE_JSON_ALT_WEEKLY_SCHEDULE 0x80
#define CONFIG_CHANGE_SCOPE_RELATIONS 0x100
