### ISSUE TITLE
Device config on Cloud - problem with brightness 0, 100% and automatic settings

### ISSUE THREAD

**Issue by fracz** [SUPLA/supla-cloud#759]
Ustawienie jasnośći ekranu w cloud na 0% powoduje dziwne efekty. Jak ustawię 0 % -> zapisz, a następnie włącze "automatic", to po zapisaniu nadal mam 0%.
Podobnie mając ustawione "automatic" - nie da się ustawić 0% - zawsze wraca do "autoatic". Trzeba jakąś pośrednią wartość zapisać i dopiero wtedy da się zapisać 0%.
I jeszcze jedna rzecz: jasność 50% -> zapisz -> ustawienie automatic -> zapisz -> odznaczam automatic i wtedy jasność jest zawsze na 100% ustawiona. Gdzieś jasność się resetuje do 100%, co chyba nie jest potrzebne - może tam zawsze zostać ostatnio używana wartość

**Comment by fracz** [comment]
> Ustawienie jasnośći ekranu w cloud na 0% powoduje dziwne efekty. Jak ustawię 0 % -> zapisz, a następnie włącze "automatic", to po zapisaniu nadal mam 0%.
> Podobnie mając ustawione "automatic" - nie da się ustawić 0% - zawsze wraca do "autoatic". Trzeba jakąś pośrednią wartość zapisać i dopiero wtedy da się zapisać 0%.

Tego nie umiem powtórzyć. U mnie działa w porządku. Czy problem nadal u Ciebie występuje @klew?

> I jeszcze jedna rzecz: jasność 50% -> zapisz -> ustawienie automatic -> zapisz -> odznaczam automatic i wtedy jasność jest zawsze na 100% ustawiona. Gdzieś jasność się resetuje do 100%, co chyba nie jest potrzebne - może tam zawsze zostać ostatnio używana wartość

Gdy ustawienia są wczytane jako "automatic" i ktoś to wyłączy to muszę jakąś wstępną wartość ustawić. Przyjąłem 100. W bazie nie przechowujemy "starej" wartości jasności, gdy jest włączone automatic.
Ustawianie i zapisywanie w kółko rzeczywiście mogłoby zapamiętać ostatnią wartość we froncie, ale to raczej wyłącznie case testowy. Specjalnie dla Ciebie zrobiłem tak, że zapamiętuje.

**Comment by klew** [comment]
Po ostatnich aktualizacjach, też już tego problemu nie widze.
Odnośnie automatic i zapamiętywania wartości - w konfiguracji są zawsze przechowywane oba parametry, więc "ręczna jasność" nie jest kasowana, gdy włącza się tryb automatyczny. Choć nie wiem jak to w tym jsonie jest zrobione.
