### ISSUE TITLE
Add "Hide disconnected" toggle in My Supla section of https://cloud.supla.org/

### ISSUE THREAD

**Issue by sirbagin** [SUPLA/supla-cloud#773]
It would nice to have toggle switch to show only connected devices in MY SUPLA section of the web interface for I/D Device and Channel view. This area can become overcrowded with devices witch are not currently in use but are kept for future reference. 
Flipping the toggle would result in cleaner view and better user experience.
This filter toggle should remain in the position set by the user after logging out.
![HIDE SUPLA](https://github.com/SUPLA/supla-cloud/assets/43033365/d6f6bea0-e233-4f45-8fc4-dd654348b949)

**Comment by fracz** [comment]
To be released in v23.12.
