### ISSUE TITLE
Support for locked devices

### ISSUE THREAD

**Issue by fracz** [SUPLA/supla-cloud#774]
Urządzenie rejestruje się z flagą LOCKED. Serwer po rejestracji odrzuca połączenie. W cloud pojawia się przycisk "Odblokuj urządzenie". Pojawia się formularz z informację "Podaj kod odblokowujący instalatora". Po wprowadzeniu cloud odpytuje jakieś API (może w AD?) czy kod jest prawidłowy i jeśli tak usuwa z bazy flagę LOCKED, informuje API, że urządzenie o nazwie XYZ, GUID, itd. się odblokowało. Urządzenie się rejestruje, serwer nie odrzuca połączenia i urządzenie usuwa z ustawień informację, że jest zablokowane.

**Comment by fracz** [comment]
Roboczo przyjąłem wartość flagi

```
DEVICE_LOCKED = 0x0080
```

**Comment by klew** [comment]
#define SUPLA_DEVICE_FLAG_DEVICE_LOCKED 0x0100            // ver. >= 22
