### ISSUE TITLE
Missing trigger field definition

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#776]
![image](https://github.com/SUPLA/supla-cloud/assets/6603397/0a742bf3-f99e-4de6-a6a4-bd73d36a25cc)

https://en-forum.supla.org/viewtopic.php?p=168409

**Comment by fracz** [comment]
Fixed. Will be out in the next release.

**Comment by zarybnickyj** [comment]
Thank you for your reaction. I tried it on release 23.12. 

All triggers can now be saved. Below my comments on each type.
1) When the valve is closed: works fine, notifications work, it can't recognize if the valve was closed automatically or manually
2) When the valve is opened: works fine, notifications work
3) When the valve is opened or closed: not tried, redundant trigger for me
4) When the valve is manually closed: notifications work, but if I have trigger 1 and 4 set at the same time, both notifications come up, it can't recognize if the valve was closed manually or automatically
5) When flooding is detected: it doesn't work or I don't know how it should work. I tried to splash the flood sensor with water, the sensor reacted immediately, the valve closed automatically, notifications 1) and 4) came, it can't recognize flood or it can't detect the closure of the valvce by the flood sensor

**Comment by przemyslawzygmunt** [comment]
Currently, there is no HW with Supla on board that would inform us whether the valve was closed due to flooding. Only the Peweko valve informs us whether the closure occurred by manual operation (or not). Will it be satisfactory for you if we allow you to pass the {{ IS_CLOSED_MANUALLY }} variable to the content of the notifications, which will assume the status "Yes" or "No". You will be able to insert it into the notification text.

**Comment by zarybnickyj** [comment]
Thank you very much, yes that would be the solution. I think it is necessary to add a check on the variable IS_CLOSED_MANUALLY , so that notifications do not come in case of trigger 1 and 4 at the same time

Přeloženo pomocí DeepL (https://www.deepl.com/app/?utm_source=ios&utm_medium=app&utm_campaign=share-translation)

**Comment by przemyslawzygmunt** [comment]
The check you are writing about is not possible to implement. I suggest simply leaving only one notification (1) and adding a different variable {{ IS_CLOSED_MANUALLY }} in the content there

**Comment by zarybnickyj** [comment]
Ok, thank you very much.
