### ISSUE TITLE
Voltage, current and power charts for energy meters.

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#789]
json config:

{ 'voltageLoggingEnabled': false, 'currentLoggingEnabled': false, 'powerActiveLoggingEnabled': false }

**Comment by fracz** [comment]
voltage ready

**Comment by przemyslawzygmunt** [comment]
{ 'voltageLoggerEnabled': false, 'currentLoggerEnabled': false, 'powerActiveLoggerEnabled': false }
