### ISSUE TITLE
Disabling scene doesn't hide actions box

### ISSUE THREAD

**Issue by jaku2019** [SUPLA/supla-cloud#796]
Dzień dobry,
wyłączenie sceny nie powoduje ukrycia pola Akcje. Po próbie uruchomienia wybranej akcji serwer oczywiście informuje o błędzie.
![image](https://github.com/SUPLA/supla-cloud/assets/55255300/316b6fd2-108a-4ebf-941a-3db9a9897167)

**Comment by fracz** [comment]
Fixed, thank you
