### ISSUE TITLE
Cannot disable device in the Cloud

### ISSUE THREAD

**Issue by jaku2019** [SUPLA/supla-cloud#797]
Dzień dobry,
w Cloudzie v23.11.02 i v24.01.01 nie da się wyłączyć urządzenia - wyskakuje błąd widoczny na załączonym zdjęciu.
![disabling_error](https://github.com/SUPLA/supla-cloud/assets/55255300/0cb4c255-7609-49c8-a6f4-d197f5aafa5a)

**Comment by fracz** [comment]
duplicates https://github.com/SUPLA/supla-cloud/issues/787
