### ISSUE TITLE
Localization search in "localization select" is not working properly

### ISSUE THREAD

**Issue by klew** [SUPLA/supla-cloud#813]
When I try to search localization by text it usually shows empty list when 2 characters are typed:

![image](https://github.com/SUPLA/supla-cloud/assets/205610/35cefdce-ecf8-44ca-bb6e-7202ed7511f7)

I.e. when I type "sa" ("SA", "Sa") there is empty list, but there are localizations with "Sam" and "Salon" names

**Comment by fracz** [comment]
Czy możesz zobaczyć czy w konsoli JS (F12->Console) są jakieś błędy? u mnie to działa poprawnie.

![image](https://github.com/SUPLA/supla-cloud/assets/3918865/9653b8b6-5b80-4b6d-9810-a2ed76770c2c)

**Comment by klew** [comment]
Obecnie u mnie też zaczęło to działać poprawnie. Zamknę issue i jeśli znów na to trafię, to sprawdzę logi i dam znać.

**Comment by fracz** [comment]
to wina tej karuzeli. Mam >10 lokalizacji. Na ekranie są 4 na raz. Przewiń na koniec i szukaj lokalizacji z początku. One się "rysują" poza ekranem i karuzela się nie przewija
jak sobie najpierw karuzelę przestawię do pierwszego elementu, to wyszukiwanie działa

**Comment by klew** [comment]
Problem jest także z "przewinięciem" karuzeli w innych miejscach. Np. tutaj screen ze scen - też pusto, mimo że sceny o nazwie "sc" istnieją:
![image](https://github.com/SUPLA/supla-cloud/assets/205610/18592a03-0812-453f-927a-c1158ba6eddb)
