### ISSUE TITLE
Too many channels visisble in "delete device" popup

### ISSUE THREAD

**Issue by klew** [SUPLA/supla-cloud#814]
When I try to delete a channel, cloud is searching for all affected channels/scenes/etc.

It should always exclude its own channels from this list. Currently they are included, when there are dependencies between channels (i.e. relay + AT).
Additionally Cloud says that associated metering channel will be removed, but it won't. Only association will be removed:
![image](https://github.com/SUPLA/supla-cloud/assets/205610/178e2117-db81-4b86-952c-fbd15db688fd)

**Comment by klew** [comment]
Duplicates #806

**Comment by fracz** [comment]
Tutaj problemem było tłumamczenie.
