### ISSUE TITLE
Additional config for electricity meters

### ISSUE THREAD

**Issue by klew** [SUPLA/supla-cloud#819]
In channel config json for electricity meter channel there will be new parameters based on this structure:
```
typedef struct {
  // Selected CT type
  unsigned _supla_int64_t UsedCTType;  // EM_CT_TYPE_
  // Selected phase LED type
  unsigned _supla_int64_t UsedPhaseLedType;  // EM_PHASE_LED_TYPE_*

  // Phase LED params (actual meaning depends on phase LED type)
  _supla_int_t PhaseLedParam1;
  _supla_int_t PhaseLedParam2;

  // readonly, device capabilities
  unsigned _supla_int64_t AvailableCTTypes;
  unsigned _supla_int64_t AvailablePhaseLedTypes;

  unsigned char Reserved[32];
} TChannelConfig_ElectricityMeter;  // v. >= 23
```

UsedCTType (used  current transformer type) - drop-down select with values based on AvailableCTTypes bitmap.
UsedPhaseLedType - drop-down select with values based on AvailablePhaseLedTypes.
When Available* field is zero, then corresponsing drop-down shouldn't be visible.

Values for CT Type:
```
#define EM_CT_TYPE_100A_33mA  (1ULL << 0)
#define EM_CT_TYPE_200A_66mA  (1ULL << 1)
#define EM_CT_TYPE_400A_133mA (1ULL << 2)
```
Corresponding labels: "100A/33.3mA", "200A/66.6mA", "400A/133.3mA".
CT types may be extended in future. So provide fallback for labels in form "Unknown CT type 4", etc. 

Values for Phase LED Types with PhaseLedParam1/2 usage description:
```
#define EM_PHASE_LED_TYPE_OFF                       (1ULL << 0)
#define EM_PHASE_LED_TYPE_VOLTAGE_PRESENCE          (1ULL << 1)
#define EM_PHASE_LED_TYPE_VOLTAGE_PRESENCE_INVERTED (1ULL << 2)
// Voltage level:
//  - PhaseLedParam1 - "low threshold", units 0.01 V.
//    When voltage < low threshold -> blue LED
//  - PhaseLedParam2 - "high threshold", units 0.01 V.
//    When voltage > high threshold -> red LED
//  - Voltage between low and high threshold -> green LED
#define EM_PHASE_LED_TYPE_VOLTAGE_LEVEL             (1ULL << 3)
// Active power direction:
//  - PhaseLedParam1 - "low threshold", units 0.01 W.
//    When power < low threshold -> green LED.
//  - PhaseLedParam2 - "high threshold", units 0.01 W.
//    When power > high threshold -> red LED
#define EM_PHASE_LED_TYPE_POWER_ACTIVE_DIRECTION    (1ULL << 4)
```

**Comment by przemyslawzygmunt** [comment]
Sample JSON below.
phaseLedParam1,phaseLedParam2 should be divided by 100.

{
   "usedCTType":"200A_66mA",
   "usedPhaseLedType":"200A_66mA",
   "phaseLedParam1":15,
   "phaseLedParam2":46,
   "availableCTTypes":[
      "100A_33mA",
      "200A_66mA",
      "400A_133mA"
   ],
   "availablePhaseLedTypes":[
      "OFF",
      "PRESENCE",
      "PRESENCE_INVERTED"
   ]
}

**Comment by fracz** [comment]
phaseLedParam1 i phaseLedParam2 - to są wartości od 0-100?

**Comment by fracz** [comment]
Czym są phaseLedParam1 i phaseLedParam2? Jakie mogą przyjmować wartości?

**Comment by fracz** [comment]
Dodałem ustawienia dla phaseLedTypes oraz CTTypes. Param1 i Param2 zostawiam do wyjaśnienia.

**Comment by fracz** [comment]
![image](https://github.com/user-attachments/assets/4a1f00d1-91d7-4d22-93dd-72dbf577c9b9)
