### ISSUE TITLE
literówka w logach na konsoli / sedning instead of sending word in the console logs

### ISSUE THREAD

**Issue by gmx168** [SUPLA/supla-cloud#832]
Zaznaczylem bold.

08:03:17.404 -> Sending device config result OK (1)
08:03:17.404 -> Send: [53 55 50 4C 41 17 05 00 00 00 B7 02 00 00 0A 00 00 00 01 00 00 00 00 00 00 00 00 00 ]
08:03:17.499 -> Send: [53 55 50 4C 41 ]
08:03:17.547 -> Relay[1]: updating timer value: remainingTime=0 state=0
**08:03:17.547 -> SRPC sedning: remaining time 0, channel 1, state 0**
08:03:17.594 -> Send: [53 55 50 4C 41 17 06 00 00 00 69 00 00 00 E3 00 00 00 01 32 DD 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ]
08:03:17.971 -> Send: [53 55 50 4C 41 ]
08:03:18.019 -> Send: [53 55 50 4C 41 17 07 00 00 00 A8 02 00 00 06 00 00 00 01 00 00 00 00 00 ]
08:03:18.066 -> Send: [53 55 50 4C 41 ]
08:03:18.161 -> Recv: [53 55 50 4C 41 17 03 00 00 00 DC 00 00 00 03 00 00 00 1E 0A F0 53 55 50 4C 41 ]
08:03:18.161 -> Activity timeout set to 30 s

**Comment by klew** [comment]
Dzięki za zgłoszenie. Poprawka wrzucona.
Na przyszłość: problemy z supla-device najlepiej zgłaszać w repozytorium supla-device, a nie supla-cloud :)
