### ISSUE TITLE
Add device config filed for TDeviceConfig_HomeScreenOffDelayType

### ISSUE THREAD

**Issue by klew** [SUPLA/supla-cloud#833]
Related issue: https://github.com/SUPLA/supla-core/issues/433

**Comment by przemyslawzygmunt** [comment]
{ "homeScreen": {"offDelayType": "alwaysEnabled"} } // Default, even if it is not set in json
{ "homeScreen": {"offDelayType": "enabledWhenDark"} }

**Comment by fracz** [comment]
![image](https://github.com/user-attachments/assets/c21aa284-b144-4a4a-8951-6b9d0320b9d7)
