### ISSUE TITLE
Add display of HVAC IsOn value in 1-100% range

### ISSUE THREAD

**Issue by klew** [SUPLA/supla-cloud#837]
So far, HVAC was reporting state in IsOn as 0 (off) or 1 (heating/cooling).
Now HVAC can also report values 2-101 (1-100 %) for partial heating. I.e. IsOn=41 -> means Heating on 40 %.
Cloud should present in channel state % value, when IsOn >= 2

**Comment by fracz** [comment]
![image](https://github.com/user-attachments/assets/ad125577-01bf-43a0-aa03-21138f347630)
