### ISSUE TITLE
Add handling of readonly and hidden parameter properties for HVAC

### ISSUE THREAD

**Issue by klew** [SUPLA/supla-cloud#841]
@przemyslawzygmunt please update details about json format.

**Comment by klew** [comment]
Readonly fileds should be visible in form, but marked as disabled/readonly.
Hidden fileds shouldn't be displayed at all for user.

**Comment by przemyslawzygmunt** [comment]
supla_iodev_channel.parameters:
*You need to check whether the size of this field will be sufficient.

{
   "readOnlyConfigFields":[
      "mainThermometerChannelNo",
      "auxThermometerChannelNo",
      "binarySensorChannelNo",
      "auxThermometerType",
      "antiFreezeAndOverheatProtectionEnabled",
      "usedAlgorithm",
      "minOnTimeS",
      "minOffTimeS",
      "outputValueOnError",
      "subfunction",
      "auxMinMaxSetpointEnabled",
      "useSeparateHeatCoolOutputs",
      "masterThermostatChannelNo",
      "heatOrColdSourceSwitchChannelNo",
      "pumpSwitchChannelNo",
      "pumpSwitchChannelNo"
   ],
   "hiddenConfigFields":[
      "mainThermometerChannelNo",
      "auxThermometerChannelNo",
      "binarySensorChannelNo",
      "auxThermometerType",
      "antiFreezeAndOverheatProtectionEnabled",
      "usedAlgorithm",
      "minOnTimeS",
      "minOffTimeS",
      "outputValueOnError",
      "subfunction",
      "auxMinMaxSetpointEnabled",
      "useSeparateHeatCoolOutputs",
      "masterThermostatChannelNo",
      "heatOrColdSourceSwitchChannelNo",
      "pumpSwitchChannelNo",
      "temperatureSetpointChangeSwitchesToManualMode"
   ],
   "readOnlyTempretureConfigFields":[
      "freezeProtection",
      "eco",
      "comfort",
      "boost",
      "heatProtection",
      "histeresis",
      "belowAlarm",
      "aboveAlarm",
      "auxMinSetpoint",
      "auxMaxSetpoint"
   ],
   "hiddenTempretureConfigFields":[
      "freezeProtection",
      "eco",
      "comfort",
      "boost",
      "heatProtection",
      "histeresis",
      "belowAlarm",
      "aboveAlarm",
      "auxMinSetpoint",
      "auxMaxSetpoint"
   ]
}

**Comment by klew** [comment]
When "subfunction" is readonly, then weekly schedule settings for another mode (heat or cool) should be hidden.

I.e. when subfunction is readonly and set to "heat", then "coolling mode" weekly schedule settings should be hidden.

**Comment by fracz** [comment]
@przemyslawzygmunt w kluczach napisałeś `readOnlyTempretureConfigFields` (temperEture) - zakładam że to literówka, i zmieniam na `readOnlyTempratureConfigFields`

**Comment by przemyslawzygmunt** [comment]
Zgadza się. Poprawiam po stronie supla-server.

**Comment by klew** [comment]
Tam jest jeszcze jedna literówka: "tempreture" -> "tempErature"

**Comment by przemyslawzygmunt** [comment]
To nie jest to samo o czym pisał @fracz ?
