### ISSUE TITLE
HVAC - can't set both min and max aux temperature setpoint, because form clears other value

### ISSUE THREAD

**Issue by klew** [SUPLA/supla-cloud#842]
It should be possible to fill both min and max aux temperatures setpoints:

![Image](https://github.com/SUPLA/supla-cloud/assets/205610/4bf27806-1976-43a9-9079-2344edb70bfa)

**Comment by fracz** [comment]
U mnie da się ustawić obydwie. Potrzebuję więcej info (np. które to urządzenie z beta?)



![Image](https://github.com/user-attachments/assets/f553531a-d51a-4cbf-9293-e8e6672ea91b)



@klew

**Comment by fracz** [comment]
Problemem był brak przekazywania `autoOffsetMin` przez properties. Założyłem, że gdy nie ma to jest `0` :-)

**Comment by klew** [comment]
"autoOffsetMin" (i Max) są do ustawiania odległości między nastawą heat i cool dla termostatów heat_cool (stare auto).
Parametry "autoOffsetMin" i "autoOffsetMax" zmieniły też nazwę jakiś czas temu i jest powinny on się nazywać "heatCoolOffsetMin" (i Max).
Natomiast nastawa dla min oraz max aux temperature setpoint, powinna być w zakresie określonym przez "auxMin" i "auxMax" (w json w config)
