### ISSUE TITLE
HVAC - add support for new configuration parameters

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#843]

**Comment by przemyslawzygmunt** [comment]
user_config:
Similarly to the case of auxThermometerChannelNo, it can be a channel number or null.

{
"masterThermostatChannelNo": null,
"heatOrColdSourceSwitchChannelNo": null,
"heatOrColdSourceSwitchChannelNo": null,
"pumpSwitchChannelNo": null
}

**Comment by klew** [comment]
There will be new functions for Relay channel type:
 - SUPLA_CHANNELFNC_PUMPSWITCH 960
 - SUPLA_CHANNELFNC_HEATORCOLDSOURCESWITCH 970

Relay channel will support it if there is corresponding function bit set:
#define SUPLA_BIT_FUNC_PUMPSWITCH 0x04000000
#define SUPLA_BIT_FUNC_HEATORCOLDSOURCESWITCH 0x08000000

Those channels design/functions will be defined later (generally, those will be on/off "relays", with dedicated icon and we have not decided yet, if it should be possible to turn on/off them from app/cloud).

New HVAC configuration parameters:
Those three new parameters can be set to channels within the same device (the same restriction as for main/aux thermometers and binary sensor).
Parameters can be readonly and/or hidden.
Additionally new parameters should be hidden:
1. "masterThermostatChannelNo" - when there is only one HVAC channel on a device (only self)
2. heatOrColdSourceSwitch, pumpSwitch - when there is no relay channel with heatOrColdSourceSwitch or pumpSwitch function on the same device.
All parameters can be set to null or to other valid channel.

Additional logic for masterThermostatChannelNo: 
1. if set to another HVAC, then thermostat will get temperature setpoints, schedules, and mode from master thermostat, so weekly schedule should be hidden, "actions" box should be hidden (with a note, that This thermostat is controlled by another device XYZ - with a link).
2. After setting the "master thermostat", user should be asked if "main/aux thermometers", "binary sensor", "heat or cold switch", and "pump switch" should be set to the same value as master - this is optional and user may stay with current config, or may modify those parameters later. We can show "same as master" for fields which share config with master thermostat. When shared parameters are modified on master thermostat, their setting should be reflected also on dependant thermostat.

**Comment by fracz** [comment]
Dodane są funkcje, dodane jest wsparcie dla `pumpSwitchChannelNo`

**Comment by fracz** [comment]
Dodano wsparcie dla `heatOrColdSourceSwitchChannelId`

![image](https://github.com/user-attachments/assets/2f049556-a9b3-4cc2-8d4a-35c20d160796)

**Comment by fracz** [comment]
![image](https://github.com/user-attachments/assets/28ff960c-8135-47f0-a37c-c21f353c2d53)
![image](https://github.com/user-attachments/assets/bb84f4cb-33ce-4126-8c1b-5289bd698b98)
![image](https://github.com/user-attachments/assets/1806cabb-4ba8-4164-b291-d0f92b746c53)

**Comment by fracz** [comment]
![image](https://github.com/user-attachments/assets/d553509b-9bab-4bda-99d6-8bfaa19be1b7)
![image](https://github.com/user-attachments/assets/cfb22515-95c2-4d42-a7df-af1bef9bad48)

**Comment by fracz** [comment]
przy "akcjach" ustawionych w różnych miejscach, można dodać gdzieś info: "ta akcja się nie wykona, bo termostat jest sterowany przez inny termostat"

**Comment by fracz** [comment]
![image](https://github.com/user-attachments/assets/e2d4c789-1976-40e4-b574-f7ebe1253192)
