### ISSUE TITLE
Better gate opening sensor names

### ISSUE THREAD

**Issue by jaku2019** [SUPLA/supla-cloud#846]
Wydaje mi się, że bardziej czytelnie byłoby, gdyby pierwsza z opcji dotycząca czujników miała wpisane
**Kanał dla czujnika całkowitego otwarcia**.
Obecny zapis nie jest do końca czytelny w wypadku, gdy do wyboru są dwie opcje czujnika. To samo dotyczy czujnika otwarcia bramy garażowej.
![ruXfdu7RE0](https://github.com/user-attachments/assets/4361b34c-c451-4ef1-a44d-8d68fc05a894)

**Comment by fracz** [comment]
Zmieniam tak:

Channel for the sensor -> Fully opened sensor for channel
Channel for the partial opening sensor -> Partially opened sensor for channel
Czujnik dla kanału -> Czujnik całkowitego otwarcia dla kanału
Kanał dla czujnika pośredniego otwarcia -> Czujnik pośredniego otwarcia dla kanału
