### ISSUE TITLE
HVAC - add ability to display and edit boost/eco/comfort temperatures

### ISSUE THREAD

**Issue by klew** [SUPLA/supla-cloud#848]
Cloud should show and allow edit of boost/eco/comfort temperatures when they are available in HVAC channel config:

![Image](https://github.com/user-attachments/assets/53b1443c-31f1-434a-8887-5f2ec92825e7)

Those temperatures should be visible at the end of "Thermometers configuration" section.
Allowed temperature range is in the "room min/max" range.

Parameters may be explicitly marked as hidden/readonly (see #841 )

**Comment by fracz** [comment]
![image](https://github.com/user-attachments/assets/1e68cb2b-0dec-459c-82a8-4da66bf67ce6)
