### ISSUE TITLE
Migrate param1,param2 to json (power switch, light switch, staircasetimer)

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#857]

**Comment by przemyslawzygmunt** [comment]
SUPLA_CHANNELFNC_LIGHTSWITCH
SUPLA_CHANNELFNC_POWERSWITCH

param1 -> relatedMeterChannelId

SUPLA_CHANNELFNC_STAIRCASETIMER

param2 -> relatedMeterChannelId

**Comment by przemyslawzygmunt** [comment]
Disconnecting the channel should not remove the "relatedMeterChannelId" key from the json but should set its value to null.

**Comment by fracz** [comment]
Kanał, który był wskazywany (IC lub EM) ustawiał w `param4` też wskazanie na kanał, który mierzy. Czy tam też mam to przenieść do JSONa? @przemyslawzygmunt

**Comment by przemyslawzygmunt** [comment]
param4 można na razie zostawić. Chyba, że chcesz to od razu posprzątać to możemy zmigrować.

**Comment by przemyslawzygmunt** [comment]
UPDATE `supla_dev_channel` SET param1 = 0, user_config = JSON_SET(IFNULL(NULLIF(user_config,''),'{}'), '$.relatedMeterChannelId', param1)  WHERE (func = 130 OR func = 140) AND param1 > 0;
UPDATE `supla_dev_channel` SET param2 = 0, user_config = JSON_SET(IFNULL(NULLIF(user_config,''),'{}'), '$.relatedMeterChannelId', param2)  WHERE func = 300 AND param2 > 0;

**Comment by fracz** [comment]
Generalnie ta ucieczka z paramsów do jsona w przypadku gdy chodzi o identyfikatory nie jest taka trywialna, bo w oparciu o to działa mechanizm wykrywania zależności przy zmianach, filtrowania itp.
