### ISSUE TITLE
Make your notification queue error-proof

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#865]

**Comment by przemyslawzygmunt** [comment]
In Statement.php line 130:
                                                                               
  SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF  
  0\x9F\x87\xB6\xF0\x9F...' for column `supla`.`supla_email_notifications`.`b  
  ody` at row 1                                                                
                                                                               

supla:cyclic:send-server-messages [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>


In DoctrineSender.php line 52:
                                                                               
  An exception occurred while executing a query: SQLSTATE[22007]: Invalid dat  
  etime format: 1366 Incorrect string value: '\xF0\x9F\x87\xB6\xF0\x9F...' fo  
  r column `supla`.`supla_email_notifications`.`body` at row 1                 
                                                                               

In ExceptionConverter.php line 117:
                                                                               
  An exception occurred while executing a query: SQLSTATE[22007]: Invalid dat  
  etime format: 1366 Incorrect string value: '\xF0\x9F\x87\xB6\xF0\x9F...' fo  
  r column `supla`.`supla_email_notifications`.`body` at row 1                 
                                                                               

In Exception.php line 28:
                                                                               
  SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF  
  0\x9F\x87\xB6\xF0\x9F...' for column `supla`.`supla_email_notifications`.`b  
  ody` at row 1                                                                
                                                                               

In Statement.php line 130:
                                                                               
  SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF  
  0\x9F\x87\xB6\xF0\x9F...' for column `supla`.`supla_email_notifications`.`b  
  ody` at row 1                                                                
                                                                               

supla:cyclic:send-server-messages [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

**Comment by fracz** [comment]
@przemyslawzygmunt chodzi o złe kodowanie w bazie mb3, które pojawia się nie wiem skąd. Nie wiem co z tym zrobić.
