### ISSUE TITLE
IFTTT Support

### ISSUE THREAD

**Issue by fracz** [SUPLA/supla-cloud#87]
https://ifttt.com/discover

**Comment by fracz** [comment]
examples of smart home integrations with IFTTT: 

* [WeMo](https://ifttt.com/wemo_switch)
* [Homeseer](https://ifttt.com/homeseer)
* [intelligent Home](https://ifttt.com/intelligent_home)
* [Gideon](https://ifttt.com/gideon)

**Comment by mizrachiran** [comment]
Hi,

I'm really expecting this feature?
Is there a rough ETA?

Thanks!

**Comment by fracz** [comment]
Currently no ETA for this, unfortunately. I guess we have to implement at least direct URLs prior to ifttt. Watch #88

**Comment by mizrachiran** [comment]
I'm looking forward to have this in Supla.
It's kind of a basic thing to have in 2018...

Good luck.

**Comment by fracz** [comment]
Won't do. https://forum.supla.org/viewtopic.php?p=43662#p43662

Possible integration with IFTTT via direct links is possible right now.
