### ISSUE TITLE
Cloud: add handling of TDeviceConfig_PowerStatusLed

### ISSUE THREAD

**Issue by fracz** [SUPLA/supla-cloud#870]

**Comment by fracz** [comment]
hę?

**Comment by przemyslawzygmunt** [comment]
Mam wątpliwości co do nazwy zmiennej w tej strukturze (natywnie) ale pomijając to, to jest to analogiczne do TDeviceConfig_StatusLed (statusLed).
json:

{"powerStatusLed":"DISABLED"}
{"powerStatusLed":"ENABLED"}

**Comment by klew** [comment]
a jakbyś chciał to ją nazwać?

**Comment by przemyslawzygmunt** [comment]
Nie pasuje mi PowerStatusLed"Type" do enabled/disabled.

**Comment by klew** [comment]
To było dodane analogicznie do status led - tam są trzy opcje, a nie tylko enabled/disabled. Popraw wedle uznania :)

**Comment by przemyslawzygmunt** [comment]
Może po prostu "Enabled" ?
 1 true, 0 false

**Comment by klew** [comment]
wolałbym aby 0 było wartością domyślmną i aby oznaczało "enabled". Jak będzie co innego, to trzeba będzie pilnować aby to dobrze ustawić

**Comment by przemyslawzygmunt** [comment]
No to "Disabled"
1 true, 0 false

**Comment by fracz** [comment]
Nic nie rozumiem. 

Czy w tym zadaniu chodzi o to, żeby dodać do `user_config` urządzenia wsparcie dla

`{powerStatusLedDisabled: true}` albo `{powerStatusLedDisabled: false}` + GUI?

**Comment by klew** [comment]
Tak

**Comment by fracz** [comment]
![image](https://github.com/user-attachments/assets/0af0ba65-a749-4351-9356-50732ecaff2f)

**Comment by przemyslawzygmunt** [comment]
{"powerStatusLed":"DISABLED"}
{"powerStatusLed":"ENABLED"}

tak to działa. Dyskusja toczyła się w odniesieniu do struktury natywnej.
