### ISSUE TITLE
Add support for direct links (without authentication)

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#88]
Example
https://svr1.supla.org/direct/123/0B3DJSAQwtTAyS3lkZHlneEgyLXM/open

**Comment by fracz** [comment]
> Pomyślałem trochę o tych urlach, poczytałem... i mam kilka przemyśleń. Np tu https://security.stackexchange.com/q/58215/94865 generalnie token o zmiennej długości od 12 do 18 alfanum case  sensitive w zupełności wystarczy. Można wykluczyć problematyczne znaki do przepisywania ręcznie, bo może zajść taka potrzeba, czyli bez `0,O,1,I,l`. Natomiast nie chcemy tego tokena raczej przechowywać w bazie otwartym tekstem danych bo przy ew wycieku będzie dość smutno. Uniemożliwi to też ukradzenie URLi gdy ktoś zgadnie nasze hasło do konta. Wygenerowany URL jest więc widoczny tylko raz przy pierwszym generowaniu a jak się zgubi to trzeba sobie generować nowy - tak samo jak token na github. Na liście urli rozpoznajemy je po nazwie i możemy zmieniać co nim można robić (włączać/wyłączać/sprawdzać stan) tak jak mówiliśmy. Tokeny siedzą w bazie przejechane przez bcrypt tak jak hasła dlatego ważna jest ich zmienna długość. Trzeba raczej pamiętać przynajmniej czas ostatniego użycia z tych urli by wiedzieć które są nieużywane. Można rozważyć pełny audyt kiedy i z jakiego IP dany URL był wywołany. Warto też pomyśleć czy nie dac możliwości generowania jednorazowych URL które po 1. Użyciu są usuwane (case z tesciowa) albo takich, które działają tylko jakiś czas (czyli data wygaśnięcia możliwa do podania). Trzeba też raczej zadbać o to by pełne adresy URL nie trafiały do access  log serwera... a przynajmniej pokazać jak skonfigurować apache by tak to działało.
