### ISSUE TITLE
HVAC: check why hidden and readoly histeresis filed is visible and editable in cloud

### ISSUE THREAD

**Issue by fracz** [SUPLA/supla-cloud#881]

**Comment by fracz** [comment]
U mnie jest disabled, gdy jest readonly i znika, gdy jest hidden

![image](https://github.com/user-attachments/assets/9c0a00b5-6a96-4a5d-bbe6-9d302dabf7f5)


Proszę o przykład kanału z bety

**Comment by klew** [comment]
W bazie były niepoprawne klucze (stare z literówką).
Temat do zamknięcia

**Comment by fracz** [comment]
Literówka po stronie serwera.
