### ISSUE TITLE
Add reactions to HVAC errors (clock error, thermometer error, battery cover open)

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#883]

**Comment by fracz** [comment]
`{on_change_to: {eq: 'on', name: 'is_battery_cover_open'}}`
`{on_change_to: {eq: 'on', name: 'thermometer_error'}}`
`{on_change_to: {eq: 'on', name: 'clock_error'}}`

wsparcie we wszystkich funkcjach HVAC_*

**Comment by klew** [comment]
Tutaj mamy dodane reakcje tylko na zgłoszenie "błędu" lub "battery cover open". Nie ma w Cloud reakcji na sytuację przeciwną, np. "Gdy pokrywa baterii zostanie zamknięta" (itp).
@przemyslawzygmunt @fracz ?
