### ISSUE TITLE
Reaction to battery level change and "battery powered" state change.

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#897]

**Comment by fracz** [comment]
@przemyslawzygmunt jakieś szczegóły, jsony?

**Comment by przemyslawzygmunt** [comment]
{"on_change_to":{"name":"battery_level", "gt":30}}

**Comment by przemyslawzygmunt** [comment]
Reakcja powinna być dostępna do ustawienia jeśli supla_dev_channel_extended_value.json_value zawiera klucz "battery_level". Np.

{\"battery_level\": 30}

**Comment by przemyslawzygmunt** [comment]
Dochodzi jeszcze jedna reakcja "Battery powered" true/false.
{"on_change_to":{"name":"battery_powered", "eg":1}}

Nazwa zmiennej w on_change_to  to "battery_powered". Reakcja dostępna jeśli supla_dev_channel_extended_value.json_value będzoe zawierać klucz "battery_powered". Np.

{"battery_powered": false}

**Comment by przemyslawzygmunt** [comment]
Aby ustalić czy kanał wspiera reakcje dla poziomu baterii lub dla statusu zasilania z baterii, cloud powinien zapytać serwer przez IPC o stan kanału ustawiając GET-CHANNEL-STATE z parametrem %getFromExtendedValue ustawionym na 1.

Jeśli otrzyma odpowiedź z wartością inną niż pusta dla %BatteryLevel i analogicznie dla  %BatteryPowered to możma uznać, że użytkownik powinien móc ustawić przedmiotowe reakcje. 

https://github.com/SUPLA/supla-core/issues/483#issuecomment-2445262873

**Comment by fracz** [comment]
![image](https://github.com/user-attachments/assets/a616222e-af93-4b7c-9963-dcaba02fc780)

**Comment by przemyslawzygmunt** [comment]
Zmiana koncepcji. Teraz stan odczytujesz bezpośrednio z bazy z supla_dev_channel_state.state.
Komenda IPC GET-CHANNEL-STATE nie będzie już dostępna. Będzie dostępna komenda UPDATE-CHANNEL-STATE, która wysyła żądanie aktualizacji stanu do urządzenia. Urządzenie odpowiada, a serwer wrzuca rezultat do bazy. Przy ustalaniu czy reakcja ma być dostęona nie jest potrzebne wywoływanie UPDATE-CHANNEL-STATE tylko wystarczy sprawdzić bazę, ale już przy wyświetlaniu statusu kanału w cloud (nowa funkcjonalność) to będzie potrzebne.

**Comment by fracz** [comment]
Zakładam, że w state będzie JSON z polem `isBatteryPowered` true/false

**Comment by przemyslawzygmunt** [comment]
{
   "switchCycleCount":1,
   "ipv4":"192.168.0.1",
   "mac":"03:00:00:00:00:00",
   "batteryLevel":4,
   "batteryPowered":true,
   "wifiRSSI":6,
   "wifiSignalStrength":7,
   "bridgeNodeOnline":true,
   "bridgeNodeSignalStrength":9,
   "uptime":10,
   "connectionUptime":11,
   "batteryHealth":12,
   "lastConnectionResetCause":13,
   "lightSourceLifespan": 14,
   "lightSourceLifespanLeft": 15,
   "lightSourceOperatingTime": 16,
   "operatingTime": 17
}

lastConnectionResetCause może przyjmować wartość tupu int ale też wartość typu ENUM.
"UNKNOWN", "ACTIVITY_TIMEOUT", "WIFI_CONNECTION_LOSTT", "SERVER_CONNECTION_LOST".
