### ISSUE TITLE
Rename all "przełącznik" to "włącznik"

### ISSUE THREAD

**Issue by klew** [SUPLA/supla-cloud#901]

**Comment by fracz** [comment]
Przełącznik źródła ciepła lub chłodu -> Włącznik źródła ciepła lub chłodu ?

**Comment by klew** [comment]
Tak, bo "przełącznik" sugeruje, że przełączamy między źródłami ciepła lub chłodu. A my włączamy/wyłączamy źródło ciepła/chłodu.
