### ISSUE TITLE
Change related channel info depending on relation direction

### ISSUE THREAD

**Issue by klew** [SUPLA/supla-cloud#902]
I.e. for "master thermostat" we see such label on both master and dependant thermostat relations info.

Is it possible to change it, so if we look at master thermostat releations, then desription will be i.e.:
"Master thermostat for: Floor Heating Controller #1" ?

And when we look at "Floor Heating Controller #1" we'll see:
"Heat montior - master thermostat"

![Image](https://github.com/user-attachments/assets/e3169bc0-2805-4692-ad3d-f37107e2c10d)

Similarly for other relations

**Comment by fracz** [comment]
![image](https://github.com/user-attachments/assets/133b5fce-b1d1-4806-a6a2-f2f114304078)
