### ISSUE TITLE
TempertureControlType for HVAC

### ISSUE THREAD

**Issue by klew** [SUPLA/supla-cloud#905]
Core issue: https://github.com/SUPLA/supla-core/issues/470

HVAC will get "TemperatureControlType" user configuration field.
It may be: not supported, room temperature, aux heater/cooler temperature.

If "not supported", then Cloud should not show this field in UI.

Room temperature is default and it is the way, how current thermostats are working: all temperature setpoints (in channel value/actions, weekly schedules etc.) are withing "room min/max" limits.

When TemperatureControlType is changed to "aux heater/cooler temperature" (name TBD), then thermostat will use "aux thermometer" as a reference temperature for thermostat controll. Consequently, all temperature setpoints (channel value, action, weekly schedules), should be within limits defined by "aux min/max" temperature limits.
It is not expected from Cloud to change/fix setpoints defined earlier in actions/schedules that may be out of allowed temperature setpoint range. Thermostat device will select closest temperature setpoint to requested value.

Temperatue control type select can be added in "thermometer configuration" section

**Comment by fracz** [comment]
Cloud pilnuje ustawień temperatury aux/room w zależności od nowego ustawienia, ale tylko przy zmianach tych temperatur - zgodnie z sugestią w opisie zadania.
