### ISSUE TITLE
Can't delete channel/subdevice with readonly relation

### ISSUE THREAD

**Issue by klew** [SUPLA/supla-cloud#906]
There are HVAC channels with readonly auxThermometerChannelId.
All HVAC channels and thermometer pointed by auxThermometerChannelId, are about to be deleted, but Cloud forbids it:

![Image](https://github.com/user-attachments/assets/0af29223-98a2-4a9b-9f74-b17946b79746)

**Comment by fracz** [comment]
1. Naprawiono usuwanie relacji RO.
2. Poprawiono komunikat, gdy nie można zmienić danego kanału w związku z tym, ze jest używany w relacji RO.

![image](https://github.com/user-attachments/assets/ed65751c-a583-4231-989f-0f042ed8d617)

**Comment by klew** [comment]
Nadal nie mogę usunąć FHC
