### ISSUE TITLE
Alorightm settings not visible when in read only mode

### ISSUE THREAD

**Issue by fracz** [SUPLA/supla-cloud#907]
nie wiem czemu, ale w Cloud nie mogę ustawić, aby pokazały się ustawienia algortymu dla HVAC. Algorytm jest "readonly", ale nie jest hidden i go nie widać:

![image](https://github.com/user-attachments/assets/78146f34-7377-412b-ad01-21aa1bc58163)

**Comment by klew** [comment]
Podobny problem - aux thermometer type jest readonly, a Cloud odblokował tego selecta:
![image](https://github.com/user-attachments/assets/24da6b18-4664-4458-86c4-33d0e348e5bf)

**Comment by klew** [comment]
Select dla algorytmu, który jest readonly (nie jest hidden) nadal nie jest widoczny w ustawieniach.

**Comment by klew** [comment]
Wyświetlanie algorytmu "readonly" zniknęło we wszystkich moich termostatach. Wcześniej w kilku było to widoczne, ale nie we wszystkich. Teraz nigdzie tego nie ma.
