### ISSUE TITLE
HVAC related exceptions for channel visibility restrictions

### ISSUE THREAD

**Issue by klew** [SUPLA/supla-cloud#910]
Currently mulitple HVAC channels may have relations to: thermometers, pumps, hocs.
It should be possible to hide selected HVAC channel without hidding its "subchannels". 

https://forum.supla.org/viewtopic.php?p=188536&sid=8e42885fc6c23cde3ebe39ee3b097508#p188536

**Comment by fracz** [comment]
Tu też potrzebuję doprecyzowania. Czy mam po prostu pozwolić na niezależne ukrywanie termometrów i kanałów HVAC?

**Comment by klew** [comment]
Na pewno powinniśmy pozwolić na ukrycie kanału "rodzica" bez wymuszania ukrywania kanałów podrzędnych.

Przykładowo, mamy dwa kanały HVAC i jeden Termometr. Oba kanały używają tego Termometru. Schowanie kanału HVAC 1 nie powinno chować kanału Termometru.

**Comment by fracz** [comment]
@klew: 
aktualnie nie widzę realnego zastosowania dla ukrywania termomtru bez ukrywania hvac.
Tzn. można by na to pozwolić - wtedy pomiar temperatury zniknie w apkach, ale termostat będize nadal działał prawidłowo, bo ukrywanie chowa w apkach, a nie w urządzeniu

**Comment by fracz** [comment]
Zmiana widoczności kanałów HVAC **NIE WPŁYWA** na widoczność kanałów zależnych (termometrów, pomp, czujników binarnych, termostatów master).
Zmiana widoczności z drugiej strony (termometrów, pomp, czujników binarnych) **WPŁYWA** na widoczność kanałów HVAC.
