### ISSUE TITLE
Add second meaning of offline parameter (2 -> online but not available)

### ISSUE THREAD

**Issue by klew** [SUPLA/supla-cloud#911]
Channel with offline == 2 is: online, but "not available".

In cloud it can be greyed out on a list and state. All actions should be disabled in UI.
It can have "Connected" label and "Not available" at the same time.

**Comment by fracz** [comment]
@przemyslawzygmunt czy w odpowiedzi na `IS-CHANNEL-CONNECTED` dostanę po prostu `CONNECTED:2`?

**Comment by przemyslawzygmunt** [comment]
Obecnie tab zwracany jest id kanału jeśli jest CONNECTED. Musiałbym to rozszerzyć np. do CONNECTED:%channelId,%connected

**Comment by fracz** [comment]
![image](https://github.com/user-attachments/assets/7dd81e4c-72b8-4648-a9b4-ad646527248d)
