### ISSUE TITLE
Device disappear from list when it contain "@" in a name

### ISSUE THREAD

**Issue by klew** [SUPLA/supla-cloud#913]
When device register with name/caption containing @, then there is empy white box in Cloud:
![image](https://github.com/user-attachments/assets/7cca11f5-dde0-43f4-8fd0-91ece49ec770)

Problem does not occur on beta-cloud. It is visible only on production servers.

https://forum.supla.org/viewtopic.php?t=16075

**Comment by fracz** [comment]
Sam wyłapałem ten błąd krótko po wydaniu i już jest naprawione - dlatego na beta jest ok. Nie spodziewałem się jednak takich urządzeń na produkcji, więc nie podnosiłem alarmu :(
