### ISSUE TITLE
Add "battery cover available" channel flag support (for reaction display)

### ISSUE THREAD

**Issue by klew** [SUPLA/supla-cloud#916]
Flag:  
SUPLA_CHANNEL_FLAG_BATTERY_COVER_AVAILABLE 0x80000000 

If flag is missing on channel (HVAC), then don't show reaction for battery cover open alarm.

**Comment by fracz** [comment]
Jak to się ma do tego, co jest w zadaniu #897 ? Czy do battery cover nie muszę sprawdzać, czy jest zasilane bateryjnie?

**Comment by klew** [comment]
Battery cover flag jest niezależne od zasilania bateryjnego.
Ta flaga jest tylko do tego, aby warunkować wyświetlanie reakcji na otwarcie pokrywy baterii.
